//===- aggregation.gpu.air.mlir ---------------------------------*- MLIR -*-===//
//
// SPDX-License-Identifier: MIT
//
// Auto-generated by programming_examples/heterogeneous_moe/kernels.py.
// This kernel is intentionally small and explicit so the same AIR source can
// be lowered to both NPU and GPU backends for the heterogeneous MoE example.
//
//===----------------------------------------------------------------------===//

module {
  func.func @aggregate_outputs_host(%experts: memref<4x32xbf16>,
                                    %weights: memref<4x2xbf16>,
                                    %output: memref<4x16xbf16>)
      attributes {llvm.emit_c_interface} {
    %c1 = arith.constant 1 : index
    %g_exp = gpu.alloc () : memref<4x32xbf16>
    %g_w = gpu.alloc () : memref<4x2xbf16>
    %g_out = gpu.alloc () : memref<4x16xbf16>
    gpu.memcpy %g_exp, %experts : memref<4x32xbf16>, memref<4x32xbf16>
    gpu.memcpy %g_w, %weights : memref<4x2xbf16>, memref<4x2xbf16>

    gpu.launch blocks(%bx, %by, %bz) in (%gridx = %c1, %gridy = %c1, %gridz = %c1)
               threads(%tx, %ty, %tz) in (%blockx = %c1, %blocky = %c1, %blockz = %c1) {
      %idx0 = arith.constant 0 : index
      %idx1 = arith.constant 1 : index
      %idx2 = arith.constant 2 : index
      %idx3 = arith.constant 3 : index
      %idx4 = arith.constant 4 : index
      %idx5 = arith.constant 5 : index
      %idx6 = arith.constant 6 : index
      %idx7 = arith.constant 7 : index
      %idx8 = arith.constant 8 : index
      %idx9 = arith.constant 9 : index
      %idx10 = arith.constant 10 : index
      %idx11 = arith.constant 11 : index
      %idx12 = arith.constant 12 : index
      %idx13 = arith.constant 13 : index
      %idx14 = arith.constant 14 : index
      %idx15 = arith.constant 15 : index
      %idx16 = arith.constant 16 : index
      %idx17 = arith.constant 17 : index
      %idx18 = arith.constant 18 : index
      %idx19 = arith.constant 19 : index
      %idx20 = arith.constant 20 : index
      %idx21 = arith.constant 21 : index
      %idx22 = arith.constant 22 : index
      %idx23 = arith.constant 23 : index
      %idx24 = arith.constant 24 : index
      %idx25 = arith.constant 25 : index
      %idx26 = arith.constant 26 : index
      %idx27 = arith.constant 27 : index
      %idx28 = arith.constant 28 : index
      %idx29 = arith.constant 29 : index
      %idx30 = arith.constant 30 : index
      %idx31 = arith.constant 31 : index
      %idx32 = arith.constant 32 : index
      %v0 = memref.load %g_w[%idx0, %idx0] : memref<4x2xbf16>
      %v1 = memref.load %g_w[%idx0, %idx1] : memref<4x2xbf16>
      %v2 = memref.load %g_exp[%idx0, %idx0] : memref<4x32xbf16>
      %v3 = memref.load %g_exp[%idx0, %idx16] : memref<4x32xbf16>
      %v4 = arith.mulf %v2, %v0 : bf16
      %v5 = arith.mulf %v3, %v1 : bf16
      %v6 = arith.addf %v4, %v5 : bf16
      memref.store %v6, %g_out[%idx0, %idx0] : memref<4x16xbf16>
      %v7 = memref.load %g_exp[%idx0, %idx1] : memref<4x32xbf16>
      %v8 = memref.load %g_exp[%idx0, %idx17] : memref<4x32xbf16>
      %v9 = arith.mulf %v7, %v0 : bf16
      %v10 = arith.mulf %v8, %v1 : bf16
      %v11 = arith.addf %v9, %v10 : bf16
      memref.store %v11, %g_out[%idx0, %idx1] : memref<4x16xbf16>
      %v12 = memref.load %g_exp[%idx0, %idx2] : memref<4x32xbf16>
      %v13 = memref.load %g_exp[%idx0, %idx18] : memref<4x32xbf16>
      %v14 = arith.mulf %v12, %v0 : bf16
      %v15 = arith.mulf %v13, %v1 : bf16
      %v16 = arith.addf %v14, %v15 : bf16
      memref.store %v16, %g_out[%idx0, %idx2] : memref<4x16xbf16>
      %v17 = memref.load %g_exp[%idx0, %idx3] : memref<4x32xbf16>
      %v18 = memref.load %g_exp[%idx0, %idx19] : memref<4x32xbf16>
      %v19 = arith.mulf %v17, %v0 : bf16
      %v20 = arith.mulf %v18, %v1 : bf16
      %v21 = arith.addf %v19, %v20 : bf16
      memref.store %v21, %g_out[%idx0, %idx3] : memref<4x16xbf16>
      %v22 = memref.load %g_exp[%idx0, %idx4] : memref<4x32xbf16>
      %v23 = memref.load %g_exp[%idx0, %idx20] : memref<4x32xbf16>
      %v24 = arith.mulf %v22, %v0 : bf16
      %v25 = arith.mulf %v23, %v1 : bf16
      %v26 = arith.addf %v24, %v25 : bf16
      memref.store %v26, %g_out[%idx0, %idx4] : memref<4x16xbf16>
      %v27 = memref.load %g_exp[%idx0, %idx5] : memref<4x32xbf16>
      %v28 = memref.load %g_exp[%idx0, %idx21] : memref<4x32xbf16>
      %v29 = arith.mulf %v27, %v0 : bf16
      %v30 = arith.mulf %v28, %v1 : bf16
      %v31 = arith.addf %v29, %v30 : bf16
      memref.store %v31, %g_out[%idx0, %idx5] : memref<4x16xbf16>
      %v32 = memref.load %g_exp[%idx0, %idx6] : memref<4x32xbf16>
      %v33 = memref.load %g_exp[%idx0, %idx22] : memref<4x32xbf16>
      %v34 = arith.mulf %v32, %v0 : bf16
      %v35 = arith.mulf %v33, %v1 : bf16
      %v36 = arith.addf %v34, %v35 : bf16
      memref.store %v36, %g_out[%idx0, %idx6] : memref<4x16xbf16>
      %v37 = memref.load %g_exp[%idx0, %idx7] : memref<4x32xbf16>
      %v38 = memref.load %g_exp[%idx0, %idx23] : memref<4x32xbf16>
      %v39 = arith.mulf %v37, %v0 : bf16
      %v40 = arith.mulf %v38, %v1 : bf16
      %v41 = arith.addf %v39, %v40 : bf16
      memref.store %v41, %g_out[%idx0, %idx7] : memref<4x16xbf16>
      %v42 = memref.load %g_exp[%idx0, %idx8] : memref<4x32xbf16>
      %v43 = memref.load %g_exp[%idx0, %idx24] : memref<4x32xbf16>
      %v44 = arith.mulf %v42, %v0 : bf16
      %v45 = arith.mulf %v43, %v1 : bf16
      %v46 = arith.addf %v44, %v45 : bf16
      memref.store %v46, %g_out[%idx0, %idx8] : memref<4x16xbf16>
      %v47 = memref.load %g_exp[%idx0, %idx9] : memref<4x32xbf16>
      %v48 = memref.load %g_exp[%idx0, %idx25] : memref<4x32xbf16>
      %v49 = arith.mulf %v47, %v0 : bf16
      %v50 = arith.mulf %v48, %v1 : bf16
      %v51 = arith.addf %v49, %v50 : bf16
      memref.store %v51, %g_out[%idx0, %idx9] : memref<4x16xbf16>
      %v52 = memref.load %g_exp[%idx0, %idx10] : memref<4x32xbf16>
      %v53 = memref.load %g_exp[%idx0, %idx26] : memref<4x32xbf16>
      %v54 = arith.mulf %v52, %v0 : bf16
      %v55 = arith.mulf %v53, %v1 : bf16
      %v56 = arith.addf %v54, %v55 : bf16
      memref.store %v56, %g_out[%idx0, %idx10] : memref<4x16xbf16>
      %v57 = memref.load %g_exp[%idx0, %idx11] : memref<4x32xbf16>
      %v58 = memref.load %g_exp[%idx0, %idx27] : memref<4x32xbf16>
      %v59 = arith.mulf %v57, %v0 : bf16
      %v60 = arith.mulf %v58, %v1 : bf16
      %v61 = arith.addf %v59, %v60 : bf16
      memref.store %v61, %g_out[%idx0, %idx11] : memref<4x16xbf16>
      %v62 = memref.load %g_exp[%idx0, %idx12] : memref<4x32xbf16>
      %v63 = memref.load %g_exp[%idx0, %idx28] : memref<4x32xbf16>
      %v64 = arith.mulf %v62, %v0 : bf16
      %v65 = arith.mulf %v63, %v1 : bf16
      %v66 = arith.addf %v64, %v65 : bf16
      memref.store %v66, %g_out[%idx0, %idx12] : memref<4x16xbf16>
      %v67 = memref.load %g_exp[%idx0, %idx13] : memref<4x32xbf16>
      %v68 = memref.load %g_exp[%idx0, %idx29] : memref<4x32xbf16>
      %v69 = arith.mulf %v67, %v0 : bf16
      %v70 = arith.mulf %v68, %v1 : bf16
      %v71 = arith.addf %v69, %v70 : bf16
      memref.store %v71, %g_out[%idx0, %idx13] : memref<4x16xbf16>
      %v72 = memref.load %g_exp[%idx0, %idx14] : memref<4x32xbf16>
      %v73 = memref.load %g_exp[%idx0, %idx30] : memref<4x32xbf16>
      %v74 = arith.mulf %v72, %v0 : bf16
      %v75 = arith.mulf %v73, %v1 : bf16
      %v76 = arith.addf %v74, %v75 : bf16
      memref.store %v76, %g_out[%idx0, %idx14] : memref<4x16xbf16>
      %v77 = memref.load %g_exp[%idx0, %idx15] : memref<4x32xbf16>
      %v78 = memref.load %g_exp[%idx0, %idx31] : memref<4x32xbf16>
      %v79 = arith.mulf %v77, %v0 : bf16
      %v80 = arith.mulf %v78, %v1 : bf16
      %v81 = arith.addf %v79, %v80 : bf16
      memref.store %v81, %g_out[%idx0, %idx15] : memref<4x16xbf16>
      %v82 = memref.load %g_w[%idx1, %idx0] : memref<4x2xbf16>
      %v83 = memref.load %g_w[%idx1, %idx1] : memref<4x2xbf16>
      %v84 = memref.load %g_exp[%idx1, %idx0] : memref<4x32xbf16>
      %v85 = memref.load %g_exp[%idx1, %idx16] : memref<4x32xbf16>
      %v86 = arith.mulf %v84, %v82 : bf16
      %v87 = arith.mulf %v85, %v83 : bf16
      %v88 = arith.addf %v86, %v87 : bf16
      memref.store %v88, %g_out[%idx1, %idx0] : memref<4x16xbf16>
      %v89 = memref.load %g_exp[%idx1, %idx1] : memref<4x32xbf16>
      %v90 = memref.load %g_exp[%idx1, %idx17] : memref<4x32xbf16>
      %v91 = arith.mulf %v89, %v82 : bf16
      %v92 = arith.mulf %v90, %v83 : bf16
      %v93 = arith.addf %v91, %v92 : bf16
      memref.store %v93, %g_out[%idx1, %idx1] : memref<4x16xbf16>
      %v94 = memref.load %g_exp[%idx1, %idx2] : memref<4x32xbf16>
      %v95 = memref.load %g_exp[%idx1, %idx18] : memref<4x32xbf16>
      %v96 = arith.mulf %v94, %v82 : bf16
      %v97 = arith.mulf %v95, %v83 : bf16
      %v98 = arith.addf %v96, %v97 : bf16
      memref.store %v98, %g_out[%idx1, %idx2] : memref<4x16xbf16>
      %v99 = memref.load %g_exp[%idx1, %idx3] : memref<4x32xbf16>
      %v100 = memref.load %g_exp[%idx1, %idx19] : memref<4x32xbf16>
      %v101 = arith.mulf %v99, %v82 : bf16
      %v102 = arith.mulf %v100, %v83 : bf16
      %v103 = arith.addf %v101, %v102 : bf16
      memref.store %v103, %g_out[%idx1, %idx3] : memref<4x16xbf16>
      %v104 = memref.load %g_exp[%idx1, %idx4] : memref<4x32xbf16>
      %v105 = memref.load %g_exp[%idx1, %idx20] : memref<4x32xbf16>
      %v106 = arith.mulf %v104, %v82 : bf16
      %v107 = arith.mulf %v105, %v83 : bf16
      %v108 = arith.addf %v106, %v107 : bf16
      memref.store %v108, %g_out[%idx1, %idx4] : memref<4x16xbf16>
      %v109 = memref.load %g_exp[%idx1, %idx5] : memref<4x32xbf16>
      %v110 = memref.load %g_exp[%idx1, %idx21] : memref<4x32xbf16>
      %v111 = arith.mulf %v109, %v82 : bf16
      %v112 = arith.mulf %v110, %v83 : bf16
      %v113 = arith.addf %v111, %v112 : bf16
      memref.store %v113, %g_out[%idx1, %idx5] : memref<4x16xbf16>
      %v114 = memref.load %g_exp[%idx1, %idx6] : memref<4x32xbf16>
      %v115 = memref.load %g_exp[%idx1, %idx22] : memref<4x32xbf16>
      %v116 = arith.mulf %v114, %v82 : bf16
      %v117 = arith.mulf %v115, %v83 : bf16
      %v118 = arith.addf %v116, %v117 : bf16
      memref.store %v118, %g_out[%idx1, %idx6] : memref<4x16xbf16>
      %v119 = memref.load %g_exp[%idx1, %idx7] : memref<4x32xbf16>
      %v120 = memref.load %g_exp[%idx1, %idx23] : memref<4x32xbf16>
      %v121 = arith.mulf %v119, %v82 : bf16
      %v122 = arith.mulf %v120, %v83 : bf16
      %v123 = arith.addf %v121, %v122 : bf16
      memref.store %v123, %g_out[%idx1, %idx7] : memref<4x16xbf16>
      %v124 = memref.load %g_exp[%idx1, %idx8] : memref<4x32xbf16>
      %v125 = memref.load %g_exp[%idx1, %idx24] : memref<4x32xbf16>
      %v126 = arith.mulf %v124, %v82 : bf16
      %v127 = arith.mulf %v125, %v83 : bf16
      %v128 = arith.addf %v126, %v127 : bf16
      memref.store %v128, %g_out[%idx1, %idx8] : memref<4x16xbf16>
      %v129 = memref.load %g_exp[%idx1, %idx9] : memref<4x32xbf16>
      %v130 = memref.load %g_exp[%idx1, %idx25] : memref<4x32xbf16>
      %v131 = arith.mulf %v129, %v82 : bf16
      %v132 = arith.mulf %v130, %v83 : bf16
      %v133 = arith.addf %v131, %v132 : bf16
      memref.store %v133, %g_out[%idx1, %idx9] : memref<4x16xbf16>
      %v134 = memref.load %g_exp[%idx1, %idx10] : memref<4x32xbf16>
      %v135 = memref.load %g_exp[%idx1, %idx26] : memref<4x32xbf16>
      %v136 = arith.mulf %v134, %v82 : bf16
      %v137 = arith.mulf %v135, %v83 : bf16
      %v138 = arith.addf %v136, %v137 : bf16
      memref.store %v138, %g_out[%idx1, %idx10] : memref<4x16xbf16>
      %v139 = memref.load %g_exp[%idx1, %idx11] : memref<4x32xbf16>
      %v140 = memref.load %g_exp[%idx1, %idx27] : memref<4x32xbf16>
      %v141 = arith.mulf %v139, %v82 : bf16
      %v142 = arith.mulf %v140, %v83 : bf16
      %v143 = arith.addf %v141, %v142 : bf16
      memref.store %v143, %g_out[%idx1, %idx11] : memref<4x16xbf16>
      %v144 = memref.load %g_exp[%idx1, %idx12] : memref<4x32xbf16>
      %v145 = memref.load %g_exp[%idx1, %idx28] : memref<4x32xbf16>
      %v146 = arith.mulf %v144, %v82 : bf16
      %v147 = arith.mulf %v145, %v83 : bf16
      %v148 = arith.addf %v146, %v147 : bf16
      memref.store %v148, %g_out[%idx1, %idx12] : memref<4x16xbf16>
      %v149 = memref.load %g_exp[%idx1, %idx13] : memref<4x32xbf16>
      %v150 = memref.load %g_exp[%idx1, %idx29] : memref<4x32xbf16>
      %v151 = arith.mulf %v149, %v82 : bf16
      %v152 = arith.mulf %v150, %v83 : bf16
      %v153 = arith.addf %v151, %v152 : bf16
      memref.store %v153, %g_out[%idx1, %idx13] : memref<4x16xbf16>
      %v154 = memref.load %g_exp[%idx1, %idx14] : memref<4x32xbf16>
      %v155 = memref.load %g_exp[%idx1, %idx30] : memref<4x32xbf16>
      %v156 = arith.mulf %v154, %v82 : bf16
      %v157 = arith.mulf %v155, %v83 : bf16
      %v158 = arith.addf %v156, %v157 : bf16
      memref.store %v158, %g_out[%idx1, %idx14] : memref<4x16xbf16>
      %v159 = memref.load %g_exp[%idx1, %idx15] : memref<4x32xbf16>
      %v160 = memref.load %g_exp[%idx1, %idx31] : memref<4x32xbf16>
      %v161 = arith.mulf %v159, %v82 : bf16
      %v162 = arith.mulf %v160, %v83 : bf16
      %v163 = arith.addf %v161, %v162 : bf16
      memref.store %v163, %g_out[%idx1, %idx15] : memref<4x16xbf16>
      %v164 = memref.load %g_w[%idx2, %idx0] : memref<4x2xbf16>
      %v165 = memref.load %g_w[%idx2, %idx1] : memref<4x2xbf16>
      %v166 = memref.load %g_exp[%idx2, %idx0] : memref<4x32xbf16>
      %v167 = memref.load %g_exp[%idx2, %idx16] : memref<4x32xbf16>
      %v168 = arith.mulf %v166, %v164 : bf16
      %v169 = arith.mulf %v167, %v165 : bf16
      %v170 = arith.addf %v168, %v169 : bf16
      memref.store %v170, %g_out[%idx2, %idx0] : memref<4x16xbf16>
      %v171 = memref.load %g_exp[%idx2, %idx1] : memref<4x32xbf16>
      %v172 = memref.load %g_exp[%idx2, %idx17] : memref<4x32xbf16>
      %v173 = arith.mulf %v171, %v164 : bf16
      %v174 = arith.mulf %v172, %v165 : bf16
      %v175 = arith.addf %v173, %v174 : bf16
      memref.store %v175, %g_out[%idx2, %idx1] : memref<4x16xbf16>
      %v176 = memref.load %g_exp[%idx2, %idx2] : memref<4x32xbf16>
      %v177 = memref.load %g_exp[%idx2, %idx18] : memref<4x32xbf16>
      %v178 = arith.mulf %v176, %v164 : bf16
      %v179 = arith.mulf %v177, %v165 : bf16
      %v180 = arith.addf %v178, %v179 : bf16
      memref.store %v180, %g_out[%idx2, %idx2] : memref<4x16xbf16>
      %v181 = memref.load %g_exp[%idx2, %idx3] : memref<4x32xbf16>
      %v182 = memref.load %g_exp[%idx2, %idx19] : memref<4x32xbf16>
      %v183 = arith.mulf %v181, %v164 : bf16
      %v184 = arith.mulf %v182, %v165 : bf16
      %v185 = arith.addf %v183, %v184 : bf16
      memref.store %v185, %g_out[%idx2, %idx3] : memref<4x16xbf16>
      %v186 = memref.load %g_exp[%idx2, %idx4] : memref<4x32xbf16>
      %v187 = memref.load %g_exp[%idx2, %idx20] : memref<4x32xbf16>
      %v188 = arith.mulf %v186, %v164 : bf16
      %v189 = arith.mulf %v187, %v165 : bf16
      %v190 = arith.addf %v188, %v189 : bf16
      memref.store %v190, %g_out[%idx2, %idx4] : memref<4x16xbf16>
      %v191 = memref.load %g_exp[%idx2, %idx5] : memref<4x32xbf16>
      %v192 = memref.load %g_exp[%idx2, %idx21] : memref<4x32xbf16>
      %v193 = arith.mulf %v191, %v164 : bf16
      %v194 = arith.mulf %v192, %v165 : bf16
      %v195 = arith.addf %v193, %v194 : bf16
      memref.store %v195, %g_out[%idx2, %idx5] : memref<4x16xbf16>
      %v196 = memref.load %g_exp[%idx2, %idx6] : memref<4x32xbf16>
      %v197 = memref.load %g_exp[%idx2, %idx22] : memref<4x32xbf16>
      %v198 = arith.mulf %v196, %v164 : bf16
      %v199 = arith.mulf %v197, %v165 : bf16
      %v200 = arith.addf %v198, %v199 : bf16
      memref.store %v200, %g_out[%idx2, %idx6] : memref<4x16xbf16>
      %v201 = memref.load %g_exp[%idx2, %idx7] : memref<4x32xbf16>
      %v202 = memref.load %g_exp[%idx2, %idx23] : memref<4x32xbf16>
      %v203 = arith.mulf %v201, %v164 : bf16
      %v204 = arith.mulf %v202, %v165 : bf16
      %v205 = arith.addf %v203, %v204 : bf16
      memref.store %v205, %g_out[%idx2, %idx7] : memref<4x16xbf16>
      %v206 = memref.load %g_exp[%idx2, %idx8] : memref<4x32xbf16>
      %v207 = memref.load %g_exp[%idx2, %idx24] : memref<4x32xbf16>
      %v208 = arith.mulf %v206, %v164 : bf16
      %v209 = arith.mulf %v207, %v165 : bf16
      %v210 = arith.addf %v208, %v209 : bf16
      memref.store %v210, %g_out[%idx2, %idx8] : memref<4x16xbf16>
      %v211 = memref.load %g_exp[%idx2, %idx9] : memref<4x32xbf16>
      %v212 = memref.load %g_exp[%idx2, %idx25] : memref<4x32xbf16>
      %v213 = arith.mulf %v211, %v164 : bf16
      %v214 = arith.mulf %v212, %v165 : bf16
      %v215 = arith.addf %v213, %v214 : bf16
      memref.store %v215, %g_out[%idx2, %idx9] : memref<4x16xbf16>
      %v216 = memref.load %g_exp[%idx2, %idx10] : memref<4x32xbf16>
      %v217 = memref.load %g_exp[%idx2, %idx26] : memref<4x32xbf16>
      %v218 = arith.mulf %v216, %v164 : bf16
      %v219 = arith.mulf %v217, %v165 : bf16
      %v220 = arith.addf %v218, %v219 : bf16
      memref.store %v220, %g_out[%idx2, %idx10] : memref<4x16xbf16>
      %v221 = memref.load %g_exp[%idx2, %idx11] : memref<4x32xbf16>
      %v222 = memref.load %g_exp[%idx2, %idx27] : memref<4x32xbf16>
      %v223 = arith.mulf %v221, %v164 : bf16
      %v224 = arith.mulf %v222, %v165 : bf16
      %v225 = arith.addf %v223, %v224 : bf16
      memref.store %v225, %g_out[%idx2, %idx11] : memref<4x16xbf16>
      %v226 = memref.load %g_exp[%idx2, %idx12] : memref<4x32xbf16>
      %v227 = memref.load %g_exp[%idx2, %idx28] : memref<4x32xbf16>
      %v228 = arith.mulf %v226, %v164 : bf16
      %v229 = arith.mulf %v227, %v165 : bf16
      %v230 = arith.addf %v228, %v229 : bf16
      memref.store %v230, %g_out[%idx2, %idx12] : memref<4x16xbf16>
      %v231 = memref.load %g_exp[%idx2, %idx13] : memref<4x32xbf16>
      %v232 = memref.load %g_exp[%idx2, %idx29] : memref<4x32xbf16>
      %v233 = arith.mulf %v231, %v164 : bf16
      %v234 = arith.mulf %v232, %v165 : bf16
      %v235 = arith.addf %v233, %v234 : bf16
      memref.store %v235, %g_out[%idx2, %idx13] : memref<4x16xbf16>
      %v236 = memref.load %g_exp[%idx2, %idx14] : memref<4x32xbf16>
      %v237 = memref.load %g_exp[%idx2, %idx30] : memref<4x32xbf16>
      %v238 = arith.mulf %v236, %v164 : bf16
      %v239 = arith.mulf %v237, %v165 : bf16
      %v240 = arith.addf %v238, %v239 : bf16
      memref.store %v240, %g_out[%idx2, %idx14] : memref<4x16xbf16>
      %v241 = memref.load %g_exp[%idx2, %idx15] : memref<4x32xbf16>
      %v242 = memref.load %g_exp[%idx2, %idx31] : memref<4x32xbf16>
      %v243 = arith.mulf %v241, %v164 : bf16
      %v244 = arith.mulf %v242, %v165 : bf16
      %v245 = arith.addf %v243, %v244 : bf16
      memref.store %v245, %g_out[%idx2, %idx15] : memref<4x16xbf16>
      %v246 = memref.load %g_w[%idx3, %idx0] : memref<4x2xbf16>
      %v247 = memref.load %g_w[%idx3, %idx1] : memref<4x2xbf16>
      %v248 = memref.load %g_exp[%idx3, %idx0] : memref<4x32xbf16>
      %v249 = memref.load %g_exp[%idx3, %idx16] : memref<4x32xbf16>
      %v250 = arith.mulf %v248, %v246 : bf16
      %v251 = arith.mulf %v249, %v247 : bf16
      %v252 = arith.addf %v250, %v251 : bf16
      memref.store %v252, %g_out[%idx3, %idx0] : memref<4x16xbf16>
      %v253 = memref.load %g_exp[%idx3, %idx1] : memref<4x32xbf16>
      %v254 = memref.load %g_exp[%idx3, %idx17] : memref<4x32xbf16>
      %v255 = arith.mulf %v253, %v246 : bf16
      %v256 = arith.mulf %v254, %v247 : bf16
      %v257 = arith.addf %v255, %v256 : bf16
      memref.store %v257, %g_out[%idx3, %idx1] : memref<4x16xbf16>
      %v258 = memref.load %g_exp[%idx3, %idx2] : memref<4x32xbf16>
      %v259 = memref.load %g_exp[%idx3, %idx18] : memref<4x32xbf16>
      %v260 = arith.mulf %v258, %v246 : bf16
      %v261 = arith.mulf %v259, %v247 : bf16
      %v262 = arith.addf %v260, %v261 : bf16
      memref.store %v262, %g_out[%idx3, %idx2] : memref<4x16xbf16>
      %v263 = memref.load %g_exp[%idx3, %idx3] : memref<4x32xbf16>
      %v264 = memref.load %g_exp[%idx3, %idx19] : memref<4x32xbf16>
      %v265 = arith.mulf %v263, %v246 : bf16
      %v266 = arith.mulf %v264, %v247 : bf16
      %v267 = arith.addf %v265, %v266 : bf16
      memref.store %v267, %g_out[%idx3, %idx3] : memref<4x16xbf16>
      %v268 = memref.load %g_exp[%idx3, %idx4] : memref<4x32xbf16>
      %v269 = memref.load %g_exp[%idx3, %idx20] : memref<4x32xbf16>
      %v270 = arith.mulf %v268, %v246 : bf16
      %v271 = arith.mulf %v269, %v247 : bf16
      %v272 = arith.addf %v270, %v271 : bf16
      memref.store %v272, %g_out[%idx3, %idx4] : memref<4x16xbf16>
      %v273 = memref.load %g_exp[%idx3, %idx5] : memref<4x32xbf16>
      %v274 = memref.load %g_exp[%idx3, %idx21] : memref<4x32xbf16>
      %v275 = arith.mulf %v273, %v246 : bf16
      %v276 = arith.mulf %v274, %v247 : bf16
      %v277 = arith.addf %v275, %v276 : bf16
      memref.store %v277, %g_out[%idx3, %idx5] : memref<4x16xbf16>
      %v278 = memref.load %g_exp[%idx3, %idx6] : memref<4x32xbf16>
      %v279 = memref.load %g_exp[%idx3, %idx22] : memref<4x32xbf16>
      %v280 = arith.mulf %v278, %v246 : bf16
      %v281 = arith.mulf %v279, %v247 : bf16
      %v282 = arith.addf %v280, %v281 : bf16
      memref.store %v282, %g_out[%idx3, %idx6] : memref<4x16xbf16>
      %v283 = memref.load %g_exp[%idx3, %idx7] : memref<4x32xbf16>
      %v284 = memref.load %g_exp[%idx3, %idx23] : memref<4x32xbf16>
      %v285 = arith.mulf %v283, %v246 : bf16
      %v286 = arith.mulf %v284, %v247 : bf16
      %v287 = arith.addf %v285, %v286 : bf16
      memref.store %v287, %g_out[%idx3, %idx7] : memref<4x16xbf16>
      %v288 = memref.load %g_exp[%idx3, %idx8] : memref<4x32xbf16>
      %v289 = memref.load %g_exp[%idx3, %idx24] : memref<4x32xbf16>
      %v290 = arith.mulf %v288, %v246 : bf16
      %v291 = arith.mulf %v289, %v247 : bf16
      %v292 = arith.addf %v290, %v291 : bf16
      memref.store %v292, %g_out[%idx3, %idx8] : memref<4x16xbf16>
      %v293 = memref.load %g_exp[%idx3, %idx9] : memref<4x32xbf16>
      %v294 = memref.load %g_exp[%idx3, %idx25] : memref<4x32xbf16>
      %v295 = arith.mulf %v293, %v246 : bf16
      %v296 = arith.mulf %v294, %v247 : bf16
      %v297 = arith.addf %v295, %v296 : bf16
      memref.store %v297, %g_out[%idx3, %idx9] : memref<4x16xbf16>
      %v298 = memref.load %g_exp[%idx3, %idx10] : memref<4x32xbf16>
      %v299 = memref.load %g_exp[%idx3, %idx26] : memref<4x32xbf16>
      %v300 = arith.mulf %v298, %v246 : bf16
      %v301 = arith.mulf %v299, %v247 : bf16
      %v302 = arith.addf %v300, %v301 : bf16
      memref.store %v302, %g_out[%idx3, %idx10] : memref<4x16xbf16>
      %v303 = memref.load %g_exp[%idx3, %idx11] : memref<4x32xbf16>
      %v304 = memref.load %g_exp[%idx3, %idx27] : memref<4x32xbf16>
      %v305 = arith.mulf %v303, %v246 : bf16
      %v306 = arith.mulf %v304, %v247 : bf16
      %v307 = arith.addf %v305, %v306 : bf16
      memref.store %v307, %g_out[%idx3, %idx11] : memref<4x16xbf16>
      %v308 = memref.load %g_exp[%idx3, %idx12] : memref<4x32xbf16>
      %v309 = memref.load %g_exp[%idx3, %idx28] : memref<4x32xbf16>
      %v310 = arith.mulf %v308, %v246 : bf16
      %v311 = arith.mulf %v309, %v247 : bf16
      %v312 = arith.addf %v310, %v311 : bf16
      memref.store %v312, %g_out[%idx3, %idx12] : memref<4x16xbf16>
      %v313 = memref.load %g_exp[%idx3, %idx13] : memref<4x32xbf16>
      %v314 = memref.load %g_exp[%idx3, %idx29] : memref<4x32xbf16>
      %v315 = arith.mulf %v313, %v246 : bf16
      %v316 = arith.mulf %v314, %v247 : bf16
      %v317 = arith.addf %v315, %v316 : bf16
      memref.store %v317, %g_out[%idx3, %idx13] : memref<4x16xbf16>
      %v318 = memref.load %g_exp[%idx3, %idx14] : memref<4x32xbf16>
      %v319 = memref.load %g_exp[%idx3, %idx30] : memref<4x32xbf16>
      %v320 = arith.mulf %v318, %v246 : bf16
      %v321 = arith.mulf %v319, %v247 : bf16
      %v322 = arith.addf %v320, %v321 : bf16
      memref.store %v322, %g_out[%idx3, %idx14] : memref<4x16xbf16>
      %v323 = memref.load %g_exp[%idx3, %idx15] : memref<4x32xbf16>
      %v324 = memref.load %g_exp[%idx3, %idx31] : memref<4x32xbf16>
      %v325 = arith.mulf %v323, %v246 : bf16
      %v326 = arith.mulf %v324, %v247 : bf16
      %v327 = arith.addf %v325, %v326 : bf16
      memref.store %v327, %g_out[%idx3, %idx15] : memref<4x16xbf16>
      gpu.terminator
    }
    gpu.memcpy %output, %g_out : memref<4x16xbf16>, memref<4x16xbf16>
    gpu.dealloc %g_exp : memref<4x32xbf16>
    gpu.dealloc %g_w : memref<4x2xbf16>
    gpu.dealloc %g_out : memref<4x16xbf16>
    return
  }
}
