# SPDX-License-Identifier: MIT

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class LinearKernelConfig:
    M: int = 4
    K: int = 64
    H: int = 64
    N: int = 32
    dtype: str = "bf16"


def kernel_config_from_manifest(manifest: dict[str, Any]) -> LinearKernelConfig:
    model = manifest["model"]
    return LinearKernelConfig(
        M=int(model["M"]),
        K=int(model["K"]),
        H=int(model["H"]),
        N=int(model["N"]),
        dtype=str(model["dtype"]),
    )


def _header(title: str) -> str:
    return f"""//===- {title} ---------------------------------*- MLIR -*-===//
//
// SPDX-License-Identifier: MIT
//
// Auto-generated by programming_examples/heterogeneous_moe/llm_linear/kernels.py.
// Kernels are intentionally explicit bring-up sources for the bf16
// LLM-linear benchmark. Herd code stages L3 operands through DMA-visible
// local memory so GPU/NPU lowering can reason about device-resident inputs.
//
//===----------------------------------------------------------------------===//

"""


def prefill_gemm_air(cfg: LinearKernelConfig) -> str:
    return _header("prefill_gemm.air.mlir") + f"""module {{
  func.func @llm_linear_prefill(%input: memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
                                %weights: memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
                                %output: memref<{cfg.M}x{cfg.H}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %m = arith.constant {cfg.M} : index
    %h = arith.constant {cfg.H} : index
    air.launch (%row, %col) in (%nrow=%m, %ncol=%h)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
          memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
          memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
      air.segment @prefill_segment
          args(%seg_row=%row, %seg_col=%col,
               %seg_in=%launch_in, %seg_w=%launch_w, %seg_out=%launch_out)
          : index, index,
            memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
            memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
            memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c_k = arith.constant {cfg.K} : index
        %c_h = arith.constant {cfg.H} : index
        %l2_in = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<1x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_k] [%c1],
                           %seg_in[%seg_row, %c0] [%c1, %c_k] [%c_k, %c1])
            : (memref<{cfg.K}x{cfg.dtype}, 1>,
               memref<{cfg.M}x{cfg.K}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0] [%c_k] [%c1],
                           %seg_w[%c0, %seg_col] [%c_k, %c1] [%c_h, %c1])
            : (memref<{cfg.K}x{cfg.dtype}, 1>,
               memref<{cfg.K}x{cfg.H}x{cfg.dtype}>)
        air.herd @prefill_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.K}x{cfg.dtype}, 1>,
              memref<{cfg.K}x{cfg.dtype}, 1>,
              memref<1x{cfg.dtype}, 1> {{
          %h0 = arith.constant 0 : index
          %h1 = arith.constant 1 : index
          %h_k = arith.constant {cfg.K} : index
          %zero = arith.constant 0.0 : {cfg.dtype}
          %l1_in = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<1x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_k] [%h1],
                             %herd_in[%h0] [%h_k] [%h1])
              : (memref<{cfg.K}x{cfg.dtype}, 2>,
                 memref<{cfg.K}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_w[%h0] [%h_k] [%h1],
                             %herd_w[%h0] [%h_k] [%h1])
              : (memref<{cfg.K}x{cfg.dtype}, 2>,
                 memref<{cfg.K}x{cfg.dtype}, 1>)

          %sum = scf.for %kk = %h0 to %h_k step %h1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %l1_in[%kk] : memref<{cfg.K}x{cfg.dtype}, 2>
            %rhs = memref.load %l1_w[%kk] : memref<{cfg.K}x{cfg.dtype}, 2>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          memref.store %sum, %l1_out[%h0] : memref<1x{cfg.dtype}, 2>
          air.dma_memcpy_nd (%herd_out[%h0] [%h1] [%h1],
                             %l1_out[%h0] [%h1] [%h1])
              : (memref<1x{cfg.dtype}, 1>, memref<1x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_row, %seg_col] [%c1, %c1] [%c_h, %c1],
                           %l2_out[%c0] [%c1] [%c1])
            : (memref<{cfg.M}x{cfg.H}x{cfg.dtype}>,
               memref<1x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def decode_gemv_air(cfg: LinearKernelConfig) -> str:
    return _header("decode_gemv.air.mlir") + f"""module {{
  func.func @llm_linear_decode(%input: memref<{cfg.H}x{cfg.dtype}>,
                               %weights: memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
                               %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n = arith.constant {cfg.N} : index
    %lane_count = arith.constant 1 : index
    air.launch (%col, %lane) in (%ncol=%n, %nlane=%lane_count)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_segment
          args(%seg_col=%col, %seg_in=%launch_in,
               %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
            memref<{cfg.N}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c_h = arith.constant {cfg.H} : index
        %c_n = arith.constant {cfg.N} : index
        %l2_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<1x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_h] [%c1],
                           %seg_in[%c0] [%c_h] [%c1])
            : (memref<{cfg.H}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0] [%c_h] [%c1],
                           %seg_w[%c0, %seg_col] [%c_h, %c1] [%c_n, %c1])
            : (memref<{cfg.H}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.N}x{cfg.dtype}>)
        air.herd @decode_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.H}x{cfg.dtype}, 1>,
              memref<{cfg.H}x{cfg.dtype}, 1>,
              memref<1x{cfg.dtype}, 1> {{
          %h0 = arith.constant 0 : index
          %h1 = arith.constant 1 : index
          %h_h = arith.constant {cfg.H} : index
          %zero = arith.constant 0.0 : {cfg.dtype}
          %l1_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<1x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_h] [%h1],
                             %herd_in[%h0] [%h_h] [%h1])
              : (memref<{cfg.H}x{cfg.dtype}, 2>,
                 memref<{cfg.H}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_w[%h0] [%h_h] [%h1],
                             %herd_w[%h0] [%h_h] [%h1])
              : (memref<{cfg.H}x{cfg.dtype}, 2>,
                 memref<{cfg.H}x{cfg.dtype}, 1>)

          %sum = scf.for %hh = %h0 to %h_h step %h1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %l1_in[%hh] : memref<{cfg.H}x{cfg.dtype}, 2>
            %rhs = memref.load %l1_w[%hh] : memref<{cfg.H}x{cfg.dtype}, 2>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          memref.store %sum, %l1_out[%h0] : memref<1x{cfg.dtype}, 2>
          air.dma_memcpy_nd (%herd_out[%h0] [%h1] [%h1],
                             %l1_out[%h0] [%h1] [%h1])
              : (memref<1x{cfg.dtype}, 1>, memref<1x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_col] [%c1] [%c1],
                           %l2_out[%c0] [%c1] [%c1])
            : (memref<{cfg.N}x{cfg.dtype}>,
               memref<1x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def emit_all_kernels(cfg: LinearKernelConfig) -> dict[str, str]:
    return {
        "prefill": prefill_gemm_air(cfg),
        "decode": decode_gemv_air(cfg),
    }


def default_air_filenames(cfg: LinearKernelConfig) -> dict[str, str]:
    suffix = f"{cfg.dtype}.air.mlir"
    return {
        "prefill": f"prefill_gemm_m{cfg.M}_k{cfg.K}_h{cfg.H}_{suffix}",
        "decode": f"decode_gemv_h{cfg.H}_n{cfg.N}_{suffix}",
    }


def write_default_air_sources(
    cfg: LinearKernelConfig, output_dir: Path
) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    names = default_air_filenames(cfg)
    sources = emit_all_kernels(cfg)
    paths: dict[str, Path] = {}
    for key, text in sources.items():
        path = output_dir / names[key]
        path.write_text(text, encoding="utf-8")
        paths[key] = path
    return paths
