# SPDX-License-Identifier: MIT

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

DecodeInt4MemoryStrategy = Literal["staged_l2", "streamed_l1"]


@dataclass(frozen=True)
class LinearKernelConfig:
    M: int = 4
    K: int = 64
    H: int = 64
    N: int = 32
    dtype: str = "bf16"


def kernel_config_from_manifest(manifest: dict[str, Any]) -> LinearKernelConfig:
    model = manifest["model"]
    return LinearKernelConfig(
        M=int(model["M"]),
        K=int(model["K"]),
        H=int(model["H"]),
        N=int(model["N"]),
        dtype=str(model["dtype"]),
    )


def _aligned_output_group(length: int) -> int:
    for group in (16, 8, 4, 2):
        if length % group == 0:
            return group
    return 1


def _aligned_prefill_output_group(cfg: LinearKernelConfig) -> int:
    for group in (16, 8, 4, 2):
        if cfg.H % group == 0 and cfg.K * group * 2 <= 32768:
            return group
    return 1


def _aligned_decode_output_group(length: int) -> int:
    return 2 if length % 2 == 0 else 1


def _require_int4_hardware_shape(cfg: LinearKernelConfig, block_size: int) -> None:
    if block_size <= 0:
        raise ValueError("decode int4 block_size must be positive")
    if cfg.H % block_size != 0:
        raise ValueError("decode int4 hardware requires H % block_size == 0")
    if cfg.N % 8 != 0:
        raise ValueError("decode int4 hardware requires N divisible by 8")


def _require_dense_decode_tile_shape(
    cfg: LinearKernelConfig, tile_h: int, output_group: int
) -> None:
    if tile_h <= 0:
        raise ValueError("dense NPU decode tile_h must be positive")
    if output_group <= 0 or cfg.N % output_group != 0:
        raise ValueError("dense NPU decode requires N divisible by output_group")
    if cfg.H > tile_h and cfg.H % tile_h != 0:
        raise ValueError(
            "dense NPU decode requires H divisible by tile_h when H exceeds tile_h"
        )


def _effective_dense_decode_tile_h(cfg: LinearKernelConfig, tile_h: int) -> int:
    if cfg.H <= tile_h:
        return cfg.H
    base_tile_count = cfg.H // tile_h
    if base_tile_count <= 8:
        return tile_h
    for tile_count in (4, 5, 6, 7, 8):
        if cfg.H % tile_count == 0:
            return cfg.H // tile_count
    return tile_h


def _header(title: str) -> str:
    return f"""//===- {title} ---------------------------------*- MLIR -*-===//
//
// SPDX-License-Identifier: MIT
//
// Auto-generated by programming_examples/heterogeneous_moe/llm_linear/kernels.py.
// Kernels are intentionally explicit bring-up sources for the bf16
// LLM-linear benchmark. Herd code stages L3 operands through DMA-visible
// local memory so GPU/NPU lowering can reason about device-resident inputs.
//
//===----------------------------------------------------------------------===//

"""


def _index_constants(count: int) -> str:
    return "\n".join(
        f"          %h{i} = arith.constant {i} : index" for i in range(count)
    )


def _grouped_reductions(
    *,
    group: int,
    reduction_extent: int,
    reduction_const: str,
    loop_var: str,
    weight_memref: str,
    dtype: str,
) -> str:
    blocks = []
    for idx in range(group):
        blocks.append(
            f"""          %sum{idx}_acc = scf.for %{loop_var} = %h0 to %{reduction_const} step %h1 iter_args(%acc = %zero_acc) -> (f32) {{
            %lhs = memref.load %l1_in[%{loop_var}] : memref<{reduction_extent}x{dtype}, 2>
            %rhs = memref.load %l1_w[%{loop_var}, %h{idx}] : memref<{weight_memref}, 2>
            %lhs_acc = arith.extf %lhs : {dtype} to f32
            %rhs_acc = arith.extf %rhs : {dtype} to f32
            %prod = arith.mulf %lhs_acc, %rhs_acc : f32
            %next = arith.addf %acc, %prod : f32
            scf.yield %next : f32
          }}
          %sum{idx} = arith.truncf %sum{idx}_acc : f32 to {dtype}"""
        )
    stores = [
        f"          memref.store %sum{idx}, %l1_out[%h{idx}] : memref<{group}x{dtype}, 2>"
        for idx in range(group)
    ]
    return "\n".join(
        ["          %zero_acc = arith.constant 0.0 : f32", *blocks, *stores]
    )


def _grouped_prefill_gemm_air(cfg: LinearKernelConfig, output_group: int) -> str:
    h_groups = cfg.H // output_group
    reductions = _grouped_reductions(
        group=output_group,
        reduction_extent=cfg.K,
        reduction_const="h_k",
        loop_var="kk",
        weight_memref=f"{cfg.K}x{output_group}x{cfg.dtype}",
        dtype=cfg.dtype,
    )
    return _header("prefill_gemm.air.mlir") + f"""module {{
  func.func @llm_linear_prefill(%input: memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
                                %weights: memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
                                %output: memref<{cfg.M}x{cfg.H}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %m = arith.constant {cfg.M} : index
    %h_groups = arith.constant {h_groups} : index
    air.launch (%row, %col_group) in (%nrow=%m, %ncol=%h_groups)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
          memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
          memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
      air.segment @prefill_segment
          args(%seg_row=%row, %seg_col_group=%col_group,
               %seg_in=%launch_in, %seg_w=%launch_w, %seg_out=%launch_out)
          : index, index,
            memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
            memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
            memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c_group = arith.constant {output_group} : index
        %c_k = arith.constant {cfg.K} : index
        %c_h = arith.constant {cfg.H} : index
        %seg_col = arith.muli %seg_col_group, %c_group : index
        %l2_in = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.K}x{output_group}x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_k] [%c1],
                           %seg_in[%seg_row, %c0] [%c1, %c_k] [%c_k, %c1])
            : (memref<{cfg.K}x{cfg.dtype}, 1>,
               memref<{cfg.M}x{cfg.K}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0, %c0] [%c_k, %c_group] [%c_group, %c1],
                           %seg_w[%c0, %seg_col] [%c_k, %c_group] [%c_h, %c1])
            : (memref<{cfg.K}x{output_group}x{cfg.dtype}, 1>,
               memref<{cfg.K}x{cfg.H}x{cfg.dtype}>)
        air.herd @prefill_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.K}x{cfg.dtype}, 1>,
              memref<{cfg.K}x{output_group}x{cfg.dtype}, 1>,
              memref<{output_group}x{cfg.dtype}, 1> {{
{_index_constants(output_group)}
          %h_k = arith.constant {cfg.K} : index
          %h_group = arith.constant {output_group} : index
          %zero = arith.constant 0.0 : {cfg.dtype}
          %l1_in = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{cfg.K}x{output_group}x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_k] [%h1],
                             %herd_in[%h0] [%h_k] [%h1])
              : (memref<{cfg.K}x{cfg.dtype}, 2>,
                 memref<{cfg.K}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_w[%h0, %h0] [%h_k, %h_group] [%h_group, %h1],
                             %herd_w[%h0, %h0] [%h_k, %h_group] [%h_group, %h1])
              : (memref<{cfg.K}x{output_group}x{cfg.dtype}, 2>,
                 memref<{cfg.K}x{output_group}x{cfg.dtype}, 1>)

{reductions}
          air.dma_memcpy_nd (%herd_out[%h0] [%h_group] [%h1],
                             %l1_out[%h0] [%h_group] [%h1])
              : (memref<{output_group}x{cfg.dtype}, 1>,
                 memref<{output_group}x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_row, %seg_col] [%c1, %c_group] [%c_h, %c1],
                           %l2_out[%c0] [%c_group] [%c1])
            : (memref<{cfg.M}x{cfg.H}x{cfg.dtype}>,
               memref<{output_group}x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def _grouped_decode_gemv_air(cfg: LinearKernelConfig, output_group: int) -> str:
    n_groups = cfg.N // output_group
    reductions = _grouped_reductions(
        group=output_group,
        reduction_extent=cfg.H,
        reduction_const="h_h",
        loop_var="hh",
        weight_memref=f"{cfg.H}x{output_group}x{cfg.dtype}",
        dtype=cfg.dtype,
    )
    return _header("decode_gemv.air.mlir") + f"""module {{
  func.func @llm_linear_decode(%input: memref<{cfg.H}x{cfg.dtype}>,
                               %weights: memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
                               %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n_groups = arith.constant {n_groups} : index
    %lane_count = arith.constant 1 : index
    air.launch (%col_group, %lane) in (%ncol=%n_groups, %nlane=%lane_count)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_segment
          args(%seg_col_group=%col_group, %seg_in=%launch_in,
               %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
            memref<{cfg.N}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c_group = arith.constant {output_group} : index
        %c_h = arith.constant {cfg.H} : index
        %c_n = arith.constant {cfg.N} : index
        %seg_col = arith.muli %seg_col_group, %c_group : index
        %l2_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_h] [%c1],
                           %seg_in[%c0] [%c_h] [%c1])
            : (memref<{cfg.H}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0, %c0] [%c_h, %c_group] [%c_group, %c1],
                           %seg_w[%c0, %seg_col] [%c_h, %c_group] [%c_n, %c1])
            : (memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.N}x{cfg.dtype}>)
        air.herd @decode_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.H}x{cfg.dtype}, 1>,
              memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>,
              memref<{output_group}x{cfg.dtype}, 1> {{
{_index_constants(output_group)}
          %h_h = arith.constant {cfg.H} : index
          %h_group = arith.constant {output_group} : index
          %zero = arith.constant 0.0 : {cfg.dtype}
          %l1_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{cfg.H}x{output_group}x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_h] [%h1],
                             %herd_in[%h0] [%h_h] [%h1])
              : (memref<{cfg.H}x{cfg.dtype}, 2>,
                 memref<{cfg.H}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_w[%h0, %h0] [%h_h, %h_group] [%h_group, %h1],
                             %herd_w[%h0, %h0] [%h_h, %h_group] [%h_group, %h1])
              : (memref<{cfg.H}x{output_group}x{cfg.dtype}, 2>,
                 memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>)

{reductions}
          air.dma_memcpy_nd (%herd_out[%h0] [%h_group] [%h1],
                             %l1_out[%h0] [%h_group] [%h1])
              : (memref<{output_group}x{cfg.dtype}, 1>,
                 memref<{output_group}x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_col] [%c_group] [%c1],
                           %l2_out[%c0] [%c_group] [%c1])
            : (memref<{cfg.N}x{cfg.dtype}>,
               memref<{output_group}x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def prefill_gemm_air(cfg: LinearKernelConfig, *, align_output_dma: bool = False) -> str:
    output_group = _aligned_prefill_output_group(cfg) if align_output_dma else 1
    if output_group > 1:
        return _grouped_prefill_gemm_air(cfg, output_group)
    if output_group == 2:
        h_groups = cfg.H // output_group
        return _header("prefill_gemm.air.mlir") + f"""module {{
  func.func @llm_linear_prefill(%input: memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
                                %weights: memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
                                %output: memref<{cfg.M}x{cfg.H}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %m = arith.constant {cfg.M} : index
    %h_groups = arith.constant {h_groups} : index
    air.launch (%row, %col_group) in (%nrow=%m, %ncol=%h_groups)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
          memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
          memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
      air.segment @prefill_segment
          args(%seg_row=%row, %seg_col_group=%col_group,
               %seg_in=%launch_in, %seg_w=%launch_w, %seg_out=%launch_out)
          : index, index,
            memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
            memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
            memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c2 = arith.constant 2 : index
        %c_k = arith.constant {cfg.K} : index
        %c_h = arith.constant {cfg.H} : index
        %seg_col = arith.muli %seg_col_group, %c2 : index
        %l2_in = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.K}x2x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<2x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_k] [%c1],
                           %seg_in[%seg_row, %c0] [%c1, %c_k] [%c_k, %c1])
            : (memref<{cfg.K}x{cfg.dtype}, 1>,
               memref<{cfg.M}x{cfg.K}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0, %c0] [%c_k, %c2] [%c2, %c1],
                           %seg_w[%c0, %seg_col] [%c_k, %c2] [%c_h, %c1])
            : (memref<{cfg.K}x2x{cfg.dtype}, 1>,
               memref<{cfg.K}x{cfg.H}x{cfg.dtype}>)
        air.herd @prefill_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.K}x{cfg.dtype}, 1>,
              memref<{cfg.K}x2x{cfg.dtype}, 1>,
              memref<2x{cfg.dtype}, 1> {{
          %h0 = arith.constant 0 : index
          %h1 = arith.constant 1 : index
          %h2 = arith.constant 2 : index
          %h_k = arith.constant {cfg.K} : index
          %zero = arith.constant 0.0 : {cfg.dtype}
          %l1_in = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{cfg.K}x2x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<2x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_k] [%h1],
                             %herd_in[%h0] [%h_k] [%h1])
              : (memref<{cfg.K}x{cfg.dtype}, 2>,
                 memref<{cfg.K}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_w[%h0, %h0] [%h_k, %h2] [%h2, %h1],
                             %herd_w[%h0, %h0] [%h_k, %h2] [%h2, %h1])
              : (memref<{cfg.K}x2x{cfg.dtype}, 2>,
                 memref<{cfg.K}x2x{cfg.dtype}, 1>)

          %sum0 = scf.for %kk = %h0 to %h_k step %h1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %l1_in[%kk] : memref<{cfg.K}x{cfg.dtype}, 2>
            %rhs = memref.load %l1_w[%kk, %h0] : memref<{cfg.K}x2x{cfg.dtype}, 2>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          %sum1 = scf.for %kk = %h0 to %h_k step %h1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %l1_in[%kk] : memref<{cfg.K}x{cfg.dtype}, 2>
            %rhs = memref.load %l1_w[%kk, %h1] : memref<{cfg.K}x2x{cfg.dtype}, 2>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          memref.store %sum0, %l1_out[%h0] : memref<2x{cfg.dtype}, 2>
          memref.store %sum1, %l1_out[%h1] : memref<2x{cfg.dtype}, 2>
          air.dma_memcpy_nd (%herd_out[%h0] [%h2] [%h1],
                             %l1_out[%h0] [%h2] [%h1])
              : (memref<2x{cfg.dtype}, 1>, memref<2x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_row, %seg_col] [%c1, %c2] [%c_h, %c1],
                           %l2_out[%c0] [%c2] [%c1])
            : (memref<{cfg.M}x{cfg.H}x{cfg.dtype}>,
               memref<2x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""

    return _header("prefill_gemm.air.mlir") + f"""module {{
  func.func @llm_linear_prefill(%input: memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
                                %weights: memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
                                %output: memref<{cfg.M}x{cfg.H}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %m = arith.constant {cfg.M} : index
    %h = arith.constant {cfg.H} : index
    air.launch (%row, %col) in (%nrow=%m, %ncol=%h)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
          memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
          memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
      air.segment @prefill_segment
          args(%seg_row=%row, %seg_col=%col,
               %seg_in=%launch_in, %seg_w=%launch_w, %seg_out=%launch_out)
          : index, index,
            memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
            memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
            memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c_k = arith.constant {cfg.K} : index
        %c_h = arith.constant {cfg.H} : index
        %l2_in = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<1x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_k] [%c1],
                           %seg_in[%seg_row, %c0] [%c1, %c_k] [%c_k, %c1])
            : (memref<{cfg.K}x{cfg.dtype}, 1>,
               memref<{cfg.M}x{cfg.K}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0] [%c_k] [%c1],
                           %seg_w[%c0, %seg_col] [%c_k, %c1] [%c_h, %c1])
            : (memref<{cfg.K}x{cfg.dtype}, 1>,
               memref<{cfg.K}x{cfg.H}x{cfg.dtype}>)
        air.herd @prefill_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.K}x{cfg.dtype}, 1>,
              memref<{cfg.K}x{cfg.dtype}, 1>,
              memref<1x{cfg.dtype}, 1> {{
          %h0 = arith.constant 0 : index
          %h1 = arith.constant 1 : index
          %h_k = arith.constant {cfg.K} : index
          %zero = arith.constant 0.0 : {cfg.dtype}
          %l1_in = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{cfg.K}x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<1x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_k] [%h1],
                             %herd_in[%h0] [%h_k] [%h1])
              : (memref<{cfg.K}x{cfg.dtype}, 2>,
                 memref<{cfg.K}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_w[%h0] [%h_k] [%h1],
                             %herd_w[%h0] [%h_k] [%h1])
              : (memref<{cfg.K}x{cfg.dtype}, 2>,
                 memref<{cfg.K}x{cfg.dtype}, 1>)

          %sum = scf.for %kk = %h0 to %h_k step %h1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %l1_in[%kk] : memref<{cfg.K}x{cfg.dtype}, 2>
            %rhs = memref.load %l1_w[%kk] : memref<{cfg.K}x{cfg.dtype}, 2>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          memref.store %sum, %l1_out[%h0] : memref<1x{cfg.dtype}, 2>
          air.dma_memcpy_nd (%herd_out[%h0] [%h1] [%h1],
                             %l1_out[%h0] [%h1] [%h1])
              : (memref<1x{cfg.dtype}, 1>, memref<1x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_row, %seg_col] [%c1, %c1] [%c_h, %c1],
                           %l2_out[%c0] [%c1] [%c1])
            : (memref<{cfg.M}x{cfg.H}x{cfg.dtype}>,
               memref<1x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def _streamed_dense_decode_gemv_air(
    cfg: LinearKernelConfig, output_group: int, tile_h: int
) -> str:
    _require_dense_decode_tile_shape(cfg, tile_h, output_group)
    large_h_streaming = cfg.H > tile_h and (cfg.H // tile_h) > 8
    effective_tile_h = _effective_dense_decode_tile_h(cfg, tile_h)
    tile_count = cfg.H // effective_tile_h
    if large_h_streaming:
        return _global_streamed_dense_decode_gemv_air(
            cfg, output_group, effective_tile_h, tile_count
        )
    n_groups = cfg.N // output_group
    index_constants = _index_constants(max(output_group, 2))
    tile_blocks = _streamed_dense_decode_tile_blocks(
        cfg=cfg,
        output_group=output_group,
        effective_tile_h=effective_tile_h,
        tile_count=tile_count,
    )
    return _header("decode_gemv.air.mlir") + f"""module {{
  func.func @llm_linear_decode(%input: memref<{cfg.H}x{cfg.dtype}>,
                               %weights: memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
                               %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n_groups = arith.constant {n_groups} : index
    %lane_count = arith.constant 1 : index
    air.launch (%col_group, %lane) in (%ncol=%n_groups, %nlane=%lane_count)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_segment
          args(%seg_col_group=%col_group, %seg_in=%launch_in,
               %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
            memref<{cfg.N}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c_group = arith.constant {output_group} : index
        %c_h = arith.constant {cfg.H} : index
        %c_n = arith.constant {cfg.N} : index
        %seg_col = arith.muli %seg_col_group, %c_group : index
        %l2_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_h] [%c1],
                           %seg_in[%c0] [%c_h] [%c1])
            : (memref<{cfg.H}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0, %c0] [%c_h, %c_group] [%c_group, %c1],
                           %seg_w[%c0, %seg_col] [%c_h, %c_group] [%c_n, %c1])
            : (memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.N}x{cfg.dtype}>)
        air.herd @decode_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.H}x{cfg.dtype}, 1>,
              memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>,
              memref<{output_group}x{cfg.dtype}, 1> {{
{index_constants}
          %h_tile_h = arith.constant {effective_tile_h} : index
          %h_tiles = arith.constant {tile_count} : index
          %h_group = arith.constant {output_group} : index
          %zero_acc_f32 = arith.constant 0.0 : f32
          %l1_in = memref.alloc() : memref<{effective_tile_h}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{effective_tile_h}x{output_group}x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 2>

{tile_blocks}
          air.dma_memcpy_nd (%herd_out[%h0] [%h_group] [%h1],
                             %l1_out[%h0] [%h_group] [%h1])
              : (memref<{output_group}x{cfg.dtype}, 1>,
                 memref<{output_group}x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_col] [%c_group] [%c1],
                           %l2_out[%c0] [%c_group] [%c1])
            : (memref<{cfg.N}x{cfg.dtype}>,
               memref<{output_group}x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def _global_streamed_dense_decode_gemv_air(
    cfg: LinearKernelConfig,
    output_group: int,
    effective_tile_h: int,
    tile_count: int,
) -> str:
    n_groups = cfg.N // output_group
    index_constants = _index_constants(max(output_group, 2))
    tile_blocks = _global_dense_decode_tile_blocks(
        cfg=cfg,
        output_group=output_group,
        effective_tile_h=effective_tile_h,
        tile_count=tile_count,
    )
    return _header("decode_gemv.air.mlir") + f"""module {{
  func.func @llm_linear_decode(%input: memref<{cfg.H}x{cfg.dtype}>,
                               %weights: memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
                               %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n_groups = arith.constant {n_groups} : index
    %lane_count = arith.constant 1 : index
    air.launch (%col_group, %lane) in (%ncol=%n_groups, %nlane=%lane_count)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_segment
          args(%seg_col_group=%col_group, %seg_in=%launch_in,
               %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
            memref<{cfg.N}x{cfg.dtype}> {{
        %c1 = arith.constant 1 : index
        %c_group = arith.constant {output_group} : index
        %seg_col = arith.muli %seg_col_group, %c_group : index
        air.herd @decode_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_col=%seg_col, %herd_in=%seg_in,
                 %herd_w=%seg_w, %herd_out=%seg_out)
            : index,
              memref<{cfg.H}x{cfg.dtype}>,
              memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
              memref<{cfg.N}x{cfg.dtype}> {{
{index_constants}
          %h_tile_h = arith.constant {effective_tile_h} : index
          %h_tiles = arith.constant {tile_count} : index
          %h_group = arith.constant {output_group} : index
          %h_n = arith.constant {cfg.N} : index
          %zero_acc_f32 = arith.constant 0.0 : f32
          %l1_in = memref.alloc() : memref<{effective_tile_h}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{effective_tile_h}x{output_group}x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 2>

{tile_blocks}
          air.dma_memcpy_nd (%herd_out[%herd_col] [%h_group] [%h1],
                             %l1_out[%h0] [%h_group] [%h1])
              : (memref<{cfg.N}x{cfg.dtype}>,
                 memref<{output_group}x{cfg.dtype}, 2>)
          air.herd_terminator
        }}
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def _streamed_dense_decode_tile_blocks(
    *,
    cfg: LinearKernelConfig,
    output_group: int,
    effective_tile_h: int,
    tile_count: int,
) -> str:
    if tile_count > 8:
        return _streamed_dense_decode_tile_loop(
            cfg=cfg,
            output_group=output_group,
            effective_tile_h=effective_tile_h,
        )
    lines: list[str] = []
    current_acc = ["%zero_acc_f32" for _ in range(output_group)]
    for tile_idx in range(tile_count):
        row_base = tile_idx * effective_tile_h
        lines.extend(
            [
                f"          %h_row_{tile_idx} = arith.constant {row_base} : index",
                "          air.dma_memcpy_nd (%l1_in[%h0] [%h_tile_h] [%h1],",
                f"                             %herd_in[%h_row_{tile_idx}] [%h_tile_h] [%h1])",
                f"              : (memref<{effective_tile_h}x{cfg.dtype}, 2>,",
                f"                 memref<{cfg.H}x{cfg.dtype}, 1>)",
                "          air.dma_memcpy_nd (%l1_w[%h0, %h0] [%h_tile_h, %h_group] [%h_group, %h1],",
                f"                             %herd_w[%h_row_{tile_idx}, %h0] [%h_tile_h, %h_group] [%h_group, %h1])",
                f"              : (memref<{effective_tile_h}x{output_group}x{cfg.dtype}, 2>,",
                f"                 memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>)",
            ]
        )
        for lane in range(output_group):
            acc_name = f"%acc{lane}_t{tile_idx}"
            lines.extend(
                [
                    f"          {acc_name} = scf.for %ii{lane}_t{tile_idx} = %h0 to %h_tile_h step %h1 iter_args(%acc = {current_acc[lane]}) -> (f32) {{",
                    f"            %lhs{lane}_t{tile_idx} = memref.load %l1_in[%ii{lane}_t{tile_idx}] : memref<{effective_tile_h}x{cfg.dtype}, 2>",
                    f"            %rhs{lane}_t{tile_idx} = memref.load %l1_w[%ii{lane}_t{tile_idx}, %h{lane}] : memref<{effective_tile_h}x{output_group}x{cfg.dtype}, 2>",
                    f"            %lhs{lane}_f32_t{tile_idx} = arith.extf %lhs{lane}_t{tile_idx} : {cfg.dtype} to f32",
                    f"            %rhs{lane}_f32_t{tile_idx} = arith.extf %rhs{lane}_t{tile_idx} : {cfg.dtype} to f32",
                    f"            %prod{lane}_t{tile_idx} = arith.mulf %lhs{lane}_f32_t{tile_idx}, %rhs{lane}_f32_t{tile_idx} : f32",
                    f"            %next{lane}_t{tile_idx} = arith.addf %acc, %prod{lane}_t{tile_idx} : f32",
                    f"            scf.yield %next{lane}_t{tile_idx} : f32",
                    "          }",
                ]
            )
            current_acc[lane] = acc_name
    for lane, acc_name in enumerate(current_acc):
        lines.extend(
            [
                f"          %sum{lane} = arith.truncf {acc_name} : f32 to {cfg.dtype}",
                f"          memref.store %sum{lane}, %l1_out[%h{lane}] : memref<{output_group}x{cfg.dtype}, 2>",
            ]
        )
    return "\n".join(lines)


def _global_dense_decode_tile_blocks(
    *,
    cfg: LinearKernelConfig,
    output_group: int,
    effective_tile_h: int,
    tile_count: int,
) -> str:
    lines: list[str] = []
    current_acc = ["%zero_acc_f32" for _ in range(output_group)]
    for tile_idx in range(tile_count):
        row_base = tile_idx * effective_tile_h
        lines.extend(
            [
                f"          %h_row_{tile_idx} = arith.constant {row_base} : index",
                "          air.dma_memcpy_nd (%l1_in[%h0] [%h_tile_h] [%h1],",
                f"                             %herd_in[%h_row_{tile_idx}] [%h_tile_h] [%h1])",
                f"              : (memref<{effective_tile_h}x{cfg.dtype}, 2>,",
                f"                 memref<{cfg.H}x{cfg.dtype}>)",
                "          air.dma_memcpy_nd (%l1_w[%h0, %h0] [%h_tile_h, %h_group] [%h_group, %h1],",
                f"                             %herd_w[%h_row_{tile_idx}, %herd_col] [%h_tile_h, %h_group] [%h_n, %h1])",
                f"              : (memref<{effective_tile_h}x{output_group}x{cfg.dtype}, 2>,",
                f"                 memref<{cfg.H}x{cfg.N}x{cfg.dtype}>)",
            ]
        )
        for lane in range(output_group):
            acc_name = f"%gacc{lane}_t{tile_idx}"
            lines.extend(
                [
                    f"          {acc_name} = scf.for %gii{lane}_t{tile_idx} = %h0 to %h_tile_h step %h1 iter_args(%acc = {current_acc[lane]}) -> (f32) {{",
                    f"            %glhs{lane}_t{tile_idx} = memref.load %l1_in[%gii{lane}_t{tile_idx}] : memref<{effective_tile_h}x{cfg.dtype}, 2>",
                    f"            %grhs{lane}_t{tile_idx} = memref.load %l1_w[%gii{lane}_t{tile_idx}, %h{lane}] : memref<{effective_tile_h}x{output_group}x{cfg.dtype}, 2>",
                    f"            %glhs{lane}_f32_t{tile_idx} = arith.extf %glhs{lane}_t{tile_idx} : {cfg.dtype} to f32",
                    f"            %grhs{lane}_f32_t{tile_idx} = arith.extf %grhs{lane}_t{tile_idx} : {cfg.dtype} to f32",
                    f"            %gprod{lane}_t{tile_idx} = arith.mulf %glhs{lane}_f32_t{tile_idx}, %grhs{lane}_f32_t{tile_idx} : f32",
                    f"            %gnext{lane}_t{tile_idx} = arith.addf %acc, %gprod{lane}_t{tile_idx} : f32",
                    f"            scf.yield %gnext{lane}_t{tile_idx} : f32",
                    "          }",
                ]
            )
            current_acc[lane] = acc_name
    for lane, acc_name in enumerate(current_acc):
        lines.extend(
            [
                f"          %gsum{lane} = arith.truncf {acc_name} : f32 to {cfg.dtype}",
                f"          memref.store %gsum{lane}, %l1_out[%h{lane}] : memref<{output_group}x{cfg.dtype}, 2>",
            ]
        )
    return "\n".join(lines)


def _streamed_dense_decode_tile_loop(
    *,
    cfg: LinearKernelConfig,
    output_group: int,
    effective_tile_h: int,
) -> str:
    return f"""          %l1_acc = memref.alloc() : memref<{output_group}xf32, 2>
          scf.for %lane_init = %h0 to %h_group step %h1 {{
            memref.store %zero_acc_f32, %l1_acc[%lane_init] : memref<{output_group}xf32, 2>
          }}
          scf.for %tile = %h0 to %h_tiles step %h1 {{
            %row_base = arith.muli %tile, %h_tile_h : index
            air.dma_memcpy_nd (%l1_in[%h0] [%h_tile_h] [%h1],
                               %herd_in[%row_base] [%h_tile_h] [%h1])
                : (memref<{effective_tile_h}x{cfg.dtype}, 2>,
                   memref<{cfg.H}x{cfg.dtype}, 1>)
            air.dma_memcpy_nd (%l1_w[%h0, %h0] [%h_tile_h, %h_group] [%h_group, %h1],
                               %herd_w[%row_base, %h0] [%h_tile_h, %h_group] [%h_group, %h1])
                : (memref<{effective_tile_h}x{output_group}x{cfg.dtype}, 2>,
                   memref<{cfg.H}x{output_group}x{cfg.dtype}, 1>)
            scf.for %lane_idx = %h0 to %h_group step %h1 {{
              %acc_start = memref.load %l1_acc[%lane_idx] : memref<{output_group}xf32, 2>
              %tile_sum_f32 = scf.for %ii = %h0 to %h_tile_h step %h1 iter_args(%acc = %acc_start) -> (f32) {{
                %lhs = memref.load %l1_in[%ii] : memref<{effective_tile_h}x{cfg.dtype}, 2>
                %rhs = memref.load %l1_w[%ii, %lane_idx] : memref<{effective_tile_h}x{output_group}x{cfg.dtype}, 2>
                %lhs_f32 = arith.extf %lhs : {cfg.dtype} to f32
                %rhs_f32 = arith.extf %rhs : {cfg.dtype} to f32
                %prod = arith.mulf %lhs_f32, %rhs_f32 : f32
                %next = arith.addf %acc, %prod : f32
                scf.yield %next : f32
              }}
              memref.store %tile_sum_f32, %l1_acc[%lane_idx] : memref<{output_group}xf32, 2>
            }}
          }}
          scf.for %lane_out = %h0 to %h_group step %h1 {{
            %sum_f32 = memref.load %l1_acc[%lane_out] : memref<{output_group}xf32, 2>
            %sum = arith.truncf %sum_f32 : f32 to {cfg.dtype}
            memref.store %sum, %l1_out[%lane_out] : memref<{output_group}x{cfg.dtype}, 2>
          }}"""


def decode_gemv_air(
    cfg: LinearKernelConfig,
    *,
    align_output_dma: bool = False,
    dense_tile_h: int | None = None,
) -> str:
    output_group = _aligned_decode_output_group(cfg.N) if align_output_dma else 1
    if dense_tile_h is not None:
        return _streamed_dense_decode_gemv_air(cfg, output_group, dense_tile_h)
    if output_group > 1:
        return _grouped_decode_gemv_air(cfg, output_group)
    if output_group == 2:
        n_groups = cfg.N // output_group
        return _header("decode_gemv.air.mlir") + f"""module {{
  func.func @llm_linear_decode(%input: memref<{cfg.H}x{cfg.dtype}>,
                               %weights: memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
                               %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n_groups = arith.constant {n_groups} : index
    %lane_count = arith.constant 1 : index
    air.launch (%col_group, %lane) in (%ncol=%n_groups, %nlane=%lane_count)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_segment
          args(%seg_col_group=%col_group, %seg_in=%launch_in,
               %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
            memref<{cfg.N}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c2 = arith.constant 2 : index
        %c_h = arith.constant {cfg.H} : index
        %c_n = arith.constant {cfg.N} : index
        %seg_col = arith.muli %seg_col_group, %c2 : index
        %l2_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.H}x2x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<2x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_h] [%c1],
                           %seg_in[%c0] [%c_h] [%c1])
            : (memref<{cfg.H}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0, %c0] [%c_h, %c2] [%c2, %c1],
                           %seg_w[%c0, %seg_col] [%c_h, %c2] [%c_n, %c1])
            : (memref<{cfg.H}x2x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.N}x{cfg.dtype}>)
        air.herd @decode_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.H}x{cfg.dtype}, 1>,
              memref<{cfg.H}x2x{cfg.dtype}, 1>,
              memref<2x{cfg.dtype}, 1> {{
          %h0 = arith.constant 0 : index
          %h1 = arith.constant 1 : index
          %h2 = arith.constant 2 : index
          %h_h = arith.constant {cfg.H} : index
          %zero = arith.constant 0.0 : {cfg.dtype}
          %l1_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{cfg.H}x2x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<2x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_h] [%h1],
                             %herd_in[%h0] [%h_h] [%h1])
              : (memref<{cfg.H}x{cfg.dtype}, 2>,
                 memref<{cfg.H}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_w[%h0, %h0] [%h_h, %h2] [%h2, %h1],
                             %herd_w[%h0, %h0] [%h_h, %h2] [%h2, %h1])
              : (memref<{cfg.H}x2x{cfg.dtype}, 2>,
                 memref<{cfg.H}x2x{cfg.dtype}, 1>)

          %sum0 = scf.for %hh = %h0 to %h_h step %h1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %l1_in[%hh] : memref<{cfg.H}x{cfg.dtype}, 2>
            %rhs = memref.load %l1_w[%hh, %h0] : memref<{cfg.H}x2x{cfg.dtype}, 2>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          %sum1 = scf.for %hh = %h0 to %h_h step %h1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %l1_in[%hh] : memref<{cfg.H}x{cfg.dtype}, 2>
            %rhs = memref.load %l1_w[%hh, %h1] : memref<{cfg.H}x2x{cfg.dtype}, 2>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          memref.store %sum0, %l1_out[%h0] : memref<2x{cfg.dtype}, 2>
          memref.store %sum1, %l1_out[%h1] : memref<2x{cfg.dtype}, 2>
          air.dma_memcpy_nd (%herd_out[%h0] [%h2] [%h1],
                             %l1_out[%h0] [%h2] [%h1])
              : (memref<2x{cfg.dtype}, 1>, memref<2x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_col] [%c2] [%c1],
                           %l2_out[%c0] [%c2] [%c1])
            : (memref<{cfg.N}x{cfg.dtype}>,
               memref<2x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""

    return _header("decode_gemv.air.mlir") + f"""module {{
  func.func @llm_linear_decode(%input: memref<{cfg.H}x{cfg.dtype}>,
                               %weights: memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
                               %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n = arith.constant {cfg.N} : index
    %lane_count = arith.constant 1 : index
    air.launch (%col, %lane) in (%ncol=%n, %nlane=%lane_count)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_segment
          args(%seg_col=%col, %seg_in=%launch_in,
               %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
            memref<{cfg.N}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c_h = arith.constant {cfg.H} : index
        %c_n = arith.constant {cfg.N} : index
        %l2_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 1>
        %l2_w = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 1>
        %l2_out = memref.alloc() : memref<1x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_h] [%c1],
                           %seg_in[%c0] [%c_h] [%c1])
            : (memref<{cfg.H}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_w[%c0] [%c_h] [%c1],
                           %seg_w[%c0, %seg_col] [%c_h, %c1] [%c_n, %c1])
            : (memref<{cfg.H}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.N}x{cfg.dtype}>)
        air.herd @decode_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<{cfg.H}x{cfg.dtype}, 1>,
              memref<{cfg.H}x{cfg.dtype}, 1>,
              memref<1x{cfg.dtype}, 1> {{
          %h0 = arith.constant 0 : index
          %h1 = arith.constant 1 : index
          %h_h = arith.constant {cfg.H} : index
          %zero = arith.constant 0.0 : {cfg.dtype}
          %l1_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 2>
          %l1_w = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 2>
          %l1_out = memref.alloc() : memref<1x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_h] [%h1],
                             %herd_in[%h0] [%h_h] [%h1])
              : (memref<{cfg.H}x{cfg.dtype}, 2>,
                 memref<{cfg.H}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_w[%h0] [%h_h] [%h1],
                             %herd_w[%h0] [%h_h] [%h1])
              : (memref<{cfg.H}x{cfg.dtype}, 2>,
                 memref<{cfg.H}x{cfg.dtype}, 1>)

          %sum = scf.for %hh = %h0 to %h_h step %h1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %l1_in[%hh] : memref<{cfg.H}x{cfg.dtype}, 2>
            %rhs = memref.load %l1_w[%hh] : memref<{cfg.H}x{cfg.dtype}, 2>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          memref.store %sum, %l1_out[%h0] : memref<1x{cfg.dtype}, 2>
          air.dma_memcpy_nd (%herd_out[%h0] [%h1] [%h1],
                             %l1_out[%h0] [%h1] [%h1])
              : (memref<1x{cfg.dtype}, 1>, memref<1x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_col] [%c1] [%c1],
                           %l2_out[%c0] [%c1] [%c1])
            : (memref<{cfg.N}x{cfg.dtype}>,
               memref<1x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def _int4_block_loop(
    *,
    block_size: int,
    block_count: int,
    blocks_per_tile: int,
    output_group: int,
    cfg: LinearKernelConfig,
) -> str:
    packed_cols_per_group = output_group // 8
    dma_tile_rows = block_size * blocks_per_tile
    return f"""          scf.for %lane_init = %h0 to %h_group step %h1 {{
            memref.store %zero_acc_f32, %l1_acc[%lane_init] : memref<{output_group}xf32, 2>
          }}
          scf.for %tile_block = %h0 to %h_dma_tiles step %h1 {{
            %tile_block_base = arith.muli %tile_block, %h_blocks_per_tile : index
            %tile_row_base = arith.muli %tile_block_base, %h_block : index
            air.dma_memcpy_nd (%l1_packed[%h0, %h0] [%h_dma_tile_rows, %h{packed_cols_per_group}] [%h{packed_cols_per_group}, %h1],
                               %herd_packed[%tile_row_base, %h0] [%h_dma_tile_rows, %h{packed_cols_per_group}] [%h{packed_cols_per_group}, %h1])
                : (memref<{dma_tile_rows}x{packed_cols_per_group}xi32, 2>,
                   memref<{cfg.H}x{packed_cols_per_group}xi32, 1>)
            scf.for %bb = %h0 to %h_blocks_per_tile step %h1 {{
              %block_index = arith.addi %tile_block_base, %bb : index
              %block_row_base = arith.muli %block_index, %h_block : index
              %local_row_base = arith.muli %bb, %h_block : index
              scf.for %lane_idx = %h0 to %h_group step %h1 {{
                %acc_start = memref.load %l1_acc[%lane_idx] : memref<{output_group}xf32, 2>
                %scale_f32 = memref.load %l1_scales[%block_index, %lane_idx] : memref<{block_count}x{output_group}xf32, 2>
                %packed_col = arith.divui %lane_idx, %h_packed_lane_count : index
                %lane_rem = arith.remui %lane_idx, %h_packed_lane_count : index
                %lane_rem_i32 = arith.index_cast %lane_rem : index to i32
                %lane_shift = arith.muli %lane_rem_i32, %shift_step : i32
                %block_sum_f32 = scf.for %ii = %h0 to %h_block step %h1 iter_args(%inner_acc = %acc_start) -> (f32) {{
                  %hh = arith.addi %block_row_base, %ii : index
                  %local_hh = arith.addi %local_row_base, %ii : index
                  %lhs = memref.load %l1_in[%hh] : memref<{cfg.H}x{cfg.dtype}, 2>
                  %packed_word = memref.load %l1_packed[%local_hh, %packed_col] : memref<{dma_tile_rows}x{packed_cols_per_group}xi32, 2>
                  %shifted = arith.shrui %packed_word, %lane_shift : i32
                  %nibble = arith.andi %shifted, %mask4 : i32
                  %is_neg = arith.cmpi uge, %nibble, %sign_bit : i32
                  %negative = arith.subi %nibble, %sign_extend_bias : i32
                  %q_i32 = arith.select %is_neg, %negative, %nibble : i32
                  %q_f32 = arith.sitofp %q_i32 : i32 to f32
                  %lhs_f32 = arith.extf %lhs : {cfg.dtype} to f32
                  %weight_f32 = arith.mulf %q_f32, %scale_f32 : f32
                  %prod = arith.mulf %lhs_f32, %weight_f32 : f32
                  %next = arith.addf %inner_acc, %prod : f32
                  scf.yield %next : f32
                }}
                memref.store %block_sum_f32, %l1_acc[%lane_idx] : memref<{output_group}xf32, 2>
              }}
            }}
          }}
          scf.for %lane_out = %h0 to %h_group step %h1 {{
            %sum_f32 = memref.load %l1_acc[%lane_out] : memref<{output_group}xf32, 2>
            %sum = arith.truncf %sum_f32 : f32 to {cfg.dtype}
            memref.store %sum, %l1_out[%lane_out] : memref<{output_group}x{cfg.dtype}, 2>
          }}"""


def _int4_global_block_loop(
    *,
    block_size: int,
    block_count: int,
    output_group: int,
    cfg: LinearKernelConfig,
) -> str:
    return f"""          air.dma_memcpy_nd (%l1_scales[%h0, %h0] [%h_blocks, %h_group] [%h_group, %h1],
                             %herd_scales[%h0, %herd_col] [%h_blocks, %h_group] [%h_n, %h1])
              : (memref<{block_count}x{output_group}xf32, 2>,
                 memref<{block_count}x{cfg.N}xf32>)
          scf.for %lane_init = %h0 to %h_group step %h1 {{
            memref.store %zero_acc_f32, %l1_acc[%lane_init] : memref<{output_group}xf32, 2>
          }}
          scf.for %block_index = %h0 to %h_blocks step %h1 {{
            %block_row_base = arith.muli %block_index, %h_block : index
            air.dma_memcpy_nd (%l1_in[%h0] [%h_block] [%h1],
                               %herd_in[%block_row_base] [%h_block] [%h1])
                : (memref<{block_size}x{cfg.dtype}, 2>,
                   memref<{cfg.H}x{cfg.dtype}>)
            air.dma_memcpy_nd (%l1_packed[%h0, %h0] [%h_block, %h1] [%h1, %h1],
                               %herd_packed[%block_row_base, %herd_col_group] [%h_block, %h1] [%h_packed_word_cols, %h1])
                : (memref<{block_size}x1xi32, 2>,
                   memref<{cfg.H}x{cfg.N // 8}xi32>)
            scf.for %lane_idx = %h0 to %h_group step %h1 {{
              %acc_start = memref.load %l1_acc[%lane_idx] : memref<{output_group}xf32, 2>
              %scale_f32 = memref.load %l1_scales[%block_index, %lane_idx] : memref<{block_count}x{output_group}xf32, 2>
              %lane_rem_i32 = arith.index_cast %lane_idx : index to i32
              %lane_shift = arith.muli %lane_rem_i32, %shift_step : i32
              %block_sum_f32 = scf.for %ii = %h0 to %h_block step %h1 iter_args(%inner_acc = %acc_start) -> (f32) {{
                %lhs = memref.load %l1_in[%ii] : memref<{block_size}x{cfg.dtype}, 2>
                %packed_word = memref.load %l1_packed[%ii, %h0] : memref<{block_size}x1xi32, 2>
                %shifted = arith.shrui %packed_word, %lane_shift : i32
                %nibble = arith.andi %shifted, %mask4 : i32
                %is_neg = arith.cmpi uge, %nibble, %sign_bit : i32
                %negative = arith.subi %nibble, %sign_extend_bias : i32
                %q_i32 = arith.select %is_neg, %negative, %nibble : i32
                %q_f32 = arith.sitofp %q_i32 : i32 to f32
                %lhs_f32 = arith.extf %lhs : {cfg.dtype} to f32
                %weight_f32 = arith.mulf %q_f32, %scale_f32 : f32
                %prod = arith.mulf %lhs_f32, %weight_f32 : f32
                %next = arith.addf %inner_acc, %prod : f32
                scf.yield %next : f32
              }}
              memref.store %block_sum_f32, %l1_acc[%lane_idx] : memref<{output_group}xf32, 2>
            }}
          }}
          scf.for %lane_out = %h0 to %h_group step %h1 {{
            %sum_f32 = memref.load %l1_acc[%lane_out] : memref<{output_group}xf32, 2>
            %sum = arith.truncf %sum_f32 : f32 to {cfg.dtype}
            memref.store %sum, %l1_out[%lane_out] : memref<{output_group}x{cfg.dtype}, 2>
          }}
          air.dma_memcpy_nd (%herd_out[%herd_col] [%h_group] [%h1],
                             %l1_out[%h0] [%h_group] [%h1])
              : (memref<{cfg.N}x{cfg.dtype}>,
                 memref<{output_group}x{cfg.dtype}, 2>)"""


def decode_int4_gemv_air(
    cfg: LinearKernelConfig,
    *,
    block_size: int = 32,
    quant_axis: int = 0,
    align_output_dma: bool = True,
    memory_strategy: DecodeInt4MemoryStrategy = "staged_l2",
) -> str:
    if memory_strategy not in {"staged_l2", "streamed_l1"}:
        raise ValueError("decode int4 memory_strategy must be staged_l2 or streamed_l1")
    if quant_axis != 0:
        raise ValueError("decode int4 hardware requires quant_axis == 0")
    _require_int4_hardware_shape(cfg, block_size)
    output_group = 8
    n_groups = cfg.N // output_group
    launch_inner_groups = min(n_groups, 256)
    if n_groups % launch_inner_groups != 0:
        raise ValueError("decode int4 hardware requires launch groups divisible by 256")
    launch_outer_groups = n_groups // launch_inner_groups
    packed_word_cols = cfg.N // 8
    packed_cols_per_group = output_group // 8
    block_count = cfg.H // block_size
    blocks_per_tile = 2 if block_count > 256 else 1
    if block_count % blocks_per_tile != 0:
        raise ValueError("decode int4 hardware requires block tiles to divide H")
    dma_tile_rows = block_size * blocks_per_tile
    dma_tile_count = block_count // blocks_per_tile
    if memory_strategy == "streamed_l1":
        reductions = _int4_global_block_loop(
            block_size=block_size,
            block_count=block_count,
            output_group=output_group,
            cfg=cfg,
        )
        return _header("decode_int4.air.mlir") + f"""module {{
  func.func @llm_linear_decode_int4(%input: memref<{cfg.H}x{cfg.dtype}>,
                                    %packed_weights: memref<{cfg.H}x{packed_word_cols}xi32>,
                                    %scales: memref<{block_count}x{cfg.N}xf32>,
                                    %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n_group_outer = arith.constant {launch_outer_groups} : index
    %n_group_inner = arith.constant {launch_inner_groups} : index
    %lane_count = arith.constant 1 : index
    air.launch (%col_group_outer, %col_group_inner, %lane) in (%nouter=%n_group_outer, %ninner=%n_group_inner, %nlane=%lane_count)
        args(%launch_in=%input, %launch_packed=%packed_weights,
             %launch_scales=%scales, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{packed_word_cols}xi32>,
          memref<{block_count}x{cfg.N}xf32>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_int4_segment
          args(%seg_col_outer=%col_group_outer, %seg_col_inner=%col_group_inner,
               %seg_in=%launch_in,
               %seg_packed=%launch_packed, %seg_scales=%launch_scales,
               %seg_out=%launch_out)
          : index,
            index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{packed_word_cols}xi32>,
            memref<{block_count}x{cfg.N}xf32>,
            memref<{cfg.N}x{cfg.dtype}> {{
        %c_group = arith.constant {output_group} : index
        %c1 = arith.constant 1 : index
        %c_launch_inner = arith.constant {launch_inner_groups} : index
        %seg_col_base = arith.muli %seg_col_outer, %c_launch_inner : index
        %seg_col_group = arith.addi %seg_col_base, %seg_col_inner : index
        %seg_col = arith.muli %seg_col_group, %c_group : index
        air.herd @decode_int4_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_col_group=%seg_col_group, %herd_col=%seg_col,
                 %herd_in=%seg_in, %herd_packed=%seg_packed,
                 %herd_scales=%seg_scales, %herd_out=%seg_out)
            : index,
              index,
              memref<{cfg.H}x{cfg.dtype}>,
              memref<{cfg.H}x{packed_word_cols}xi32>,
              memref<{block_count}x{cfg.N}xf32>,
              memref<{cfg.N}x{cfg.dtype}> {{
{_index_constants(output_group)}
          %h_block = arith.constant {block_size} : index
          %h_blocks = arith.constant {block_count} : index
          %h_group = arith.constant {output_group} : index
          %h_n = arith.constant {cfg.N} : index
          %h_packed_word_cols = arith.constant {packed_word_cols} : index
          %zero_acc_f32 = arith.constant 0.0 : f32
          %shift_step = arith.constant 4 : i32
          %mask4 = arith.constant 15 : i32
          %sign_bit = arith.constant 8 : i32
          %sign_extend_bias = arith.constant 16 : i32
          %l1_in = memref.alloc() : memref<{block_size}x{cfg.dtype}, 2>
          %l1_packed = memref.alloc() : memref<{block_size}x1xi32, 2>
          %l1_scales = memref.alloc() : memref<{block_count}x{output_group}xf32, 2>
          %l1_acc = memref.alloc() : memref<{output_group}xf32, 2>
          %l1_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 2>

{reductions}
          air.herd_terminator
        }}
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""
    reductions = _int4_block_loop(
        block_size=block_size,
        block_count=block_count,
        blocks_per_tile=blocks_per_tile,
        output_group=output_group,
        cfg=cfg,
    )
    return _header("decode_int4.air.mlir") + f"""module {{
  func.func @llm_linear_decode_int4(%input: memref<{cfg.H}x{cfg.dtype}>,
                                    %packed_weights: memref<{cfg.H}x{packed_word_cols}xi32>,
                                    %scales: memref<{block_count}x{cfg.N}xf32>,
                                    %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n_group_outer = arith.constant {launch_outer_groups} : index
    %n_group_inner = arith.constant {launch_inner_groups} : index
    %lane_count = arith.constant 1 : index
    air.launch (%col_group_outer, %col_group_inner, %lane) in (%nouter=%n_group_outer, %ninner=%n_group_inner, %nlane=%lane_count)
        args(%launch_in=%input, %launch_packed=%packed_weights,
             %launch_scales=%scales, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{packed_word_cols}xi32>,
          memref<{block_count}x{cfg.N}xf32>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_int4_segment
          args(%seg_col_outer=%col_group_outer, %seg_col_inner=%col_group_inner,
               %seg_in=%launch_in,
               %seg_packed=%launch_packed, %seg_scales=%launch_scales,
               %seg_out=%launch_out)
          : index,
            index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{packed_word_cols}xi32>,
            memref<{block_count}x{cfg.N}xf32>,
            memref<{cfg.N}x{cfg.dtype}> {{
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c_group = arith.constant {output_group} : index
        %c_h = arith.constant {cfg.H} : index
        %c_n = arith.constant {cfg.N} : index
        %c_packed_word_cols = arith.constant {packed_word_cols} : index
        %c_packed_group_cols = arith.constant {packed_cols_per_group} : index
        %c_blocks = arith.constant {block_count} : index
        %c_launch_inner = arith.constant {launch_inner_groups} : index
        %seg_col_base = arith.muli %seg_col_outer, %c_launch_inner : index
        %seg_col_group = arith.addi %seg_col_base, %seg_col_inner : index
        %seg_col = arith.muli %seg_col_group, %c_group : index
        %seg_col_word = arith.muli %seg_col_group, %c_packed_group_cols : index
        %l2_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 1>
        %l2_packed = memref.alloc() : memref<{cfg.H}x{packed_cols_per_group}xi32, 1>
        %l2_scales = memref.alloc() : memref<{block_count}x{output_group}xf32, 1>
        %l2_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 1>

        air.dma_memcpy_nd (%l2_in[%c0] [%c_h] [%c1],
                           %seg_in[%c0] [%c_h] [%c1])
            : (memref<{cfg.H}x{cfg.dtype}, 1>,
               memref<{cfg.H}x{cfg.dtype}>)
        air.dma_memcpy_nd (%l2_packed[%c0, %c0] [%c_h, %c_packed_group_cols] [%c_packed_group_cols, %c1],
                           %seg_packed[%c0, %seg_col_word] [%c_h, %c_packed_group_cols] [%c_packed_word_cols, %c1])
            : (memref<{cfg.H}x{packed_cols_per_group}xi32, 1>,
               memref<{cfg.H}x{packed_word_cols}xi32>)
        air.dma_memcpy_nd (%l2_scales[%c0, %c0] [%c_blocks, %c_group] [%c_group, %c1],
                           %seg_scales[%c0, %seg_col] [%c_blocks, %c_group] [%c_n, %c1])
            : (memref<{block_count}x{output_group}xf32, 1>,
               memref<{block_count}x{cfg.N}xf32>)
        air.herd @decode_int4_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_packed=%l2_packed,
                 %herd_scales=%l2_scales, %herd_out=%l2_out)
            : memref<{cfg.H}x{cfg.dtype}, 1>,
              memref<{cfg.H}x{packed_cols_per_group}xi32, 1>,
              memref<{block_count}x{output_group}xf32, 1>,
              memref<{output_group}x{cfg.dtype}, 1> {{
{_index_constants(output_group)}
          %h_h = arith.constant {cfg.H} : index
          %h_block = arith.constant {block_size} : index
          %h_blocks = arith.constant {block_count} : index
          %h_blocks_per_tile = arith.constant {blocks_per_tile} : index
          %h_dma_tiles = arith.constant {dma_tile_count} : index
          %h_dma_tile_rows = arith.constant {dma_tile_rows} : index
          %h_group = arith.constant {output_group} : index
          %h_packed_lane_count = arith.constant 8 : index
          %zero_acc = arith.constant 0.0 : {cfg.dtype}
          %zero_acc_f32 = arith.constant 0.0 : f32
          %shift_step = arith.constant 4 : i32
          %mask4 = arith.constant 15 : i32
          %sign_bit = arith.constant 8 : i32
          %sign_extend_bias = arith.constant 16 : i32
          %l1_in = memref.alloc() : memref<{cfg.H}x{cfg.dtype}, 2>
          %l1_packed = memref.alloc() : memref<{dma_tile_rows}x{packed_cols_per_group}xi32, 2>
          %l1_scales = memref.alloc() : memref<{block_count}x{output_group}xf32, 2>
          %l1_acc = memref.alloc() : memref<{output_group}xf32, 2>
          %l1_out = memref.alloc() : memref<{output_group}x{cfg.dtype}, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_h] [%h1],
                             %herd_in[%h0] [%h_h] [%h1])
              : (memref<{cfg.H}x{cfg.dtype}, 2>,
                 memref<{cfg.H}x{cfg.dtype}, 1>)
          air.dma_memcpy_nd (%l1_scales[%h0, %h0] [%h_blocks, %h_group] [%h_group, %h1],
                             %herd_scales[%h0, %h0] [%h_blocks, %h_group] [%h_group, %h1])
              : (memref<{block_count}x{output_group}xf32, 2>,
                 memref<{block_count}x{output_group}xf32, 1>)

{reductions}
          air.dma_memcpy_nd (%herd_out[%h0] [%h_group] [%h1],
                             %l1_out[%h0] [%h_group] [%h1])
              : (memref<{output_group}x{cfg.dtype}, 1>, memref<{output_group}x{cfg.dtype}, 2>)
          air.herd_terminator
        }}

        air.dma_memcpy_nd (%seg_out[%seg_col] [%c_group] [%c1],
                           %l2_out[%c0] [%c_group] [%c1])
            : (memref<{cfg.N}x{cfg.dtype}>,
               memref<{output_group}x{cfg.dtype}, 1>)
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def emit_all_kernels(
    cfg: LinearKernelConfig,
    *,
    align_output_dma: bool = False,
    dense_decode_tile_h: int | None = None,
    include_decode_int4: bool = False,
    decode_int4_block_size: int = 32,
    decode_int4_quant_axis: int = 0,
    decode_int4_memory_strategy: DecodeInt4MemoryStrategy = "staged_l2",
) -> dict[str, str]:
    kernels = {
        "prefill": prefill_gemm_air(cfg, align_output_dma=align_output_dma),
        "decode": decode_gemv_air(
            cfg,
            align_output_dma=align_output_dma,
            dense_tile_h=dense_decode_tile_h,
        ),
    }
    if include_decode_int4:
        kernels["decode_int4"] = decode_int4_gemv_air(
            cfg,
            block_size=decode_int4_block_size,
            quant_axis=decode_int4_quant_axis,
            align_output_dma=align_output_dma,
            memory_strategy=decode_int4_memory_strategy,
        )
    return kernels


def default_air_filenames(
    cfg: LinearKernelConfig,
    *,
    include_decode_int4: bool = False,
    decode_int4_block_size: int = 32,
) -> dict[str, str]:
    suffix = f"{cfg.dtype}.air.mlir"
    names = {
        "prefill": f"prefill_gemm_m{cfg.M}_k{cfg.K}_h{cfg.H}_{suffix}",
        "decode": f"decode_gemv_h{cfg.H}_n{cfg.N}_{suffix}",
    }
    if include_decode_int4:
        names["decode_int4"] = (
            f"decode_int4_h{cfg.H}_n{cfg.N}_b{decode_int4_block_size}_{suffix}"
        )
    return names


def write_default_air_sources(
    cfg: LinearKernelConfig,
    output_dir: Path,
    *,
    align_output_dma: bool = False,
    dense_decode_tile_h: int | None = None,
    include_decode_int4: bool = False,
    decode_int4_block_size: int = 32,
    decode_int4_quant_axis: int = 0,
    decode_int4_memory_strategy: DecodeInt4MemoryStrategy = "staged_l2",
) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    names = default_air_filenames(
        cfg,
        include_decode_int4=include_decode_int4,
        decode_int4_block_size=decode_int4_block_size,
    )
    sources = emit_all_kernels(
        cfg,
        align_output_dma=align_output_dma,
        dense_decode_tile_h=dense_decode_tile_h,
        include_decode_int4=include_decode_int4,
        decode_int4_block_size=decode_int4_block_size,
        decode_int4_quant_axis=decode_int4_quant_axis,
        decode_int4_memory_strategy=decode_int4_memory_strategy,
    )
    paths: dict[str, Path] = {}
    for key, text in sources.items():
        path = output_dir / names[key]
        path.write_text(text, encoding="utf-8")
        paths[key] = path
    return paths
