# SPDX-License-Identifier: MIT

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class LinearKernelConfig:
    M: int = 4
    K: int = 64
    H: int = 64
    N: int = 32
    dtype: str = "bf16"


def kernel_config_from_manifest(manifest: dict[str, Any]) -> LinearKernelConfig:
    model = manifest["model"]
    return LinearKernelConfig(
        M=int(model["M"]),
        K=int(model["K"]),
        H=int(model["H"]),
        N=int(model["N"]),
        dtype=str(model["dtype"]),
    )


def _header(title: str) -> str:
    return f"""//===- {title} ---------------------------------*- MLIR -*-===//
//
// SPDX-License-Identifier: MIT
//
// Auto-generated by programming_examples/heterogeneous_moe/llm_linear/kernels.py.
// Milestone 1 kernels are intentionally explicit bring-up sources for the
// bf16 host-staged LLM-linear benchmark.
//
//===----------------------------------------------------------------------===//

"""


def prefill_gemm_air(cfg: LinearKernelConfig) -> str:
    return _header("prefill_gemm.air.mlir") + f"""module {{
  func.func @llm_linear_prefill(%input: memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
                                %weights: memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
                                %output: memref<{cfg.M}x{cfg.H}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %m = arith.constant {cfg.M} : index
    %h = arith.constant {cfg.H} : index
    %k = arith.constant {cfg.K} : index
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    air.launch (%row, %col) in (%nrow=%m, %ncol=%h)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
          memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
          memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
      air.segment @prefill_segment
          args(%seg_row=%row, %seg_col=%col,
               %seg_in=%launch_in, %seg_w=%launch_w, %seg_out=%launch_out)
          : index, index,
            memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
            memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
            memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
        air.herd @prefill_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_row=%seg_row, %herd_col=%seg_col,
                 %herd_in=%seg_in, %herd_w=%seg_w, %herd_out=%seg_out)
            : index, index,
              memref<{cfg.M}x{cfg.K}x{cfg.dtype}>,
              memref<{cfg.K}x{cfg.H}x{cfg.dtype}>,
              memref<{cfg.M}x{cfg.H}x{cfg.dtype}> {{
          %zero = arith.constant 0.0 : {cfg.dtype}
          %sum = scf.for %kk = %c0 to %k step %c1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %herd_in[%herd_row, %kk] : memref<{cfg.M}x{cfg.K}x{cfg.dtype}>
            %rhs = memref.load %herd_w[%kk, %herd_col] : memref<{cfg.K}x{cfg.H}x{cfg.dtype}>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          memref.store %sum, %herd_out[%herd_row, %herd_col] : memref<{cfg.M}x{cfg.H}x{cfg.dtype}>
          air.herd_terminator
        }}
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def decode_gemv_air(cfg: LinearKernelConfig) -> str:
    return _header("decode_gemv.air.mlir") + f"""module {{
  func.func @llm_linear_decode(%input: memref<{cfg.H}x{cfg.dtype}>,
                               %weights: memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
                               %output: memref<{cfg.N}x{cfg.dtype}>)
      attributes {{llvm.emit_c_interface}} {{
    %n = arith.constant {cfg.N} : index
    %h = arith.constant {cfg.H} : index
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    air.launch (%col, %lane) in (%ncol=%n, %nlane=%c1)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<{cfg.H}x{cfg.dtype}>,
          memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
          memref<{cfg.N}x{cfg.dtype}> {{
      air.segment @decode_segment
          args(%seg_col=%col, %seg_in=%launch_in,
               %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<{cfg.H}x{cfg.dtype}>,
            memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
            memref<{cfg.N}x{cfg.dtype}> {{
        air.herd @decode_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_col=%seg_col,
                 %herd_in=%seg_in, %herd_w=%seg_w, %herd_out=%seg_out)
            : index,
              memref<{cfg.H}x{cfg.dtype}>,
              memref<{cfg.H}x{cfg.N}x{cfg.dtype}>,
              memref<{cfg.N}x{cfg.dtype}> {{
          %zero = arith.constant 0.0 : {cfg.dtype}
          %sum = scf.for %hh = %c0 to %h step %c1 iter_args(%acc = %zero) -> ({cfg.dtype}) {{
            %lhs = memref.load %herd_in[%hh] : memref<{cfg.H}x{cfg.dtype}>
            %rhs = memref.load %herd_w[%hh, %herd_col] : memref<{cfg.H}x{cfg.N}x{cfg.dtype}>
            %prod = arith.mulf %lhs, %rhs : {cfg.dtype}
            %next = arith.addf %acc, %prod : {cfg.dtype}
            scf.yield %next : {cfg.dtype}
          }}
          memref.store %sum, %herd_out[%herd_col] : memref<{cfg.N}x{cfg.dtype}>
          air.herd_terminator
        }}
        air.segment_terminator
      }}
      air.launch_terminator
    }}
    return
  }}
}}
"""


def emit_all_kernels(cfg: LinearKernelConfig) -> dict[str, str]:
    return {
        "prefill": prefill_gemm_air(cfg),
        "decode": decode_gemv_air(cfg),
    }


def default_air_filenames(cfg: LinearKernelConfig) -> dict[str, str]:
    suffix = f"{cfg.dtype}.air.mlir"
    return {
        "prefill": f"prefill_gemm_m{cfg.M}_k{cfg.K}_h{cfg.H}_{suffix}",
        "decode": f"decode_gemv_h{cfg.H}_n{cfg.N}_{suffix}",
    }


def write_default_air_sources(
    cfg: LinearKernelConfig, output_dir: Path
) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    names = default_air_filenames(cfg)
    sources = emit_all_kernels(cfg)
    paths: dict[str, Path] = {}
    for key, text in sources.items():
        path = output_dir / names[key]
        path.write_text(text, encoding="utf-8")
        paths[key] = path
    return paths
