//===- aggregation.air.mlir ---------------------------------*- MLIR -*-===//
//
// SPDX-License-Identifier: MIT
//
// Auto-generated by programming_examples/heterogeneous_moe/kernels.py.
// This kernel is intentionally small and explicit so the same AIR source can
// be lowered to both NPU and GPU backends for the heterogeneous MoE example.
//
//===----------------------------------------------------------------------===//

module {
  func.func @aggregate_outputs(%experts: memref<4x2x16xf16>,
                               %weights: memref<4x2xf16>,
                               %output: memref<4x16xf16>)
      attributes {llvm.emit_c_interface} {
    %batch = arith.constant 4 : index
    %one = arith.constant 1 : index
    air.launch (%tok, %lane) in (%ntok=%batch, %nlane=%one)
        args(%launch_exp=%experts, %launch_w=%weights, %launch_out=%output)
        : memref<4x2x16xf16>,
          memref<4x2xf16>,
          memref<4x16xf16> {
      air.segment @aggregation_segment
          args(%seg_tok=%tok, %seg_exp=%launch_exp, %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<4x2x16xf16>,
            memref<4x2xf16>,
            memref<4x16xf16> {
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c2 = arith.constant 2 : index
        %c_hidden = arith.constant 16 : index
        %l2_exp = memref.alloc() : memref<1x2x16xf16, 1>
        %l2_w = memref.alloc() : memref<1x2xf16, 1>
        %l2_out = memref.alloc() : memref<1x16xf16, 1>

        air.dma_memcpy_nd (%l2_exp[%c0, %c0, %c0] [%c1, %c2, %c_hidden] [%c2, %c_hidden, %c1],
                           %seg_exp[%seg_tok, %c0, %c0] [%c1, %c2, %c_hidden] [%c2, %c_hidden, %c1])
            : (memref<1x2x16xf16, 1>,
               memref<4x2x16xf16>)
        air.dma_memcpy_nd (%l2_w[%c0, %c0] [%c1, %c2] [%c2, %c1],
                           %seg_w[%seg_tok, %c0] [%c1, %c2] [%c2, %c1])
            : (memref<1x2xf16, 1>,
               memref<4x2xf16>)

        air.herd @aggregation_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_exp=%l2_exp, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<1x2x16xf16, 1>,
              memref<1x2xf16, 1>,
              memref<1x16xf16, 1> {
          %h0 = arith.constant 0 : index
          %h1 = arith.constant 1 : index
          %h2 = arith.constant 2 : index
          %h_hidden = arith.constant 16 : index
          %l1_exp = memref.alloc() : memref<2x16xf16, 2>
          %l1_w = memref.alloc() : memref<2xf16, 2>
          %l1_out = memref.alloc() : memref<16xf16, 2>

          air.dma_memcpy_nd (%l1_exp[%h0, %h0] [%h2, %h_hidden] [%h_hidden, %h1],
                             %herd_exp[%h0, %h0, %h0] [%h1, %h2, %h_hidden] [%h2, %h_hidden, %h1])
              : (memref<2x16xf16, 2>,
                 memref<1x2x16xf16, 1>)
          air.dma_memcpy_nd (%l1_w[%h0] [%h2] [%h1],
                             %herd_w[%h0, %h0] [%h1, %h2] [%h2, %h1])
              : (memref<2xf16, 2>, memref<1x2xf16, 1>)

          %w0 = memref.load %l1_w[%h0] : memref<2xf16, 2>
          %w1 = memref.load %l1_w[%h1] : memref<2xf16, 2>
          scf.for %i = %h0 to %h_hidden step %h1 {
            %lhs = memref.load %l1_exp[%h0, %i] : memref<2x16xf16, 2>
            %rhs = memref.load %l1_exp[%h1, %i] : memref<2x16xf16, 2>
            %lhs_scaled = arith.mulf %lhs, %w0 : f16
            %rhs_scaled = arith.mulf %rhs, %w1 : f16
            %sum = arith.addf %lhs_scaled, %rhs_scaled : f16
            memref.store %sum, %l1_out[%i] : memref<16xf16, 2>
          }

          air.dma_memcpy_nd (%herd_out[%h0, %h0] [%h1, %h_hidden] [%h_hidden, %h1],
                             %l1_out[%h0] [%h_hidden] [%h1])
              : (memref<1x16xf16, 1>,
                 memref<16xf16, 2>)
          air.herd_terminator
        }

        air.dma_memcpy_nd (%seg_out[%seg_tok, %c0] [%c1, %c_hidden] [%c_hidden, %c1],
                           %l2_out[%c0, %c0] [%c1, %c_hidden] [%c_hidden, %c1])
            : (memref<4x16xf16>,
               memref<1x16xf16, 1>)
        air.segment_terminator
      }
      air.launch_terminator
    }
    return
  }
}
