//===- router_math.air.mlir ---------------------------------*- MLIR -*-===//
//
// SPDX-License-Identifier: MIT
//
// Auto-generated by programming_examples/heterogeneous_moe/kernels.py.
// This kernel is intentionally small and explicit so the same AIR source can
// be lowered to both NPU and GPU backends for the heterogeneous MoE example.
//
//===----------------------------------------------------------------------===//

module {
  func.func @router_math(%input: memref<4x16xf16>,
                         %weights: memref<16x2xf16>,
                         %output: memref<4x2xf16>)
      attributes {llvm.emit_c_interface} {
    %batch = arith.constant 4 : index
    %one = arith.constant 1 : index
    air.launch (%tok, %lane) in (%ntok=%batch, %nlane=%one)
        args(%launch_in=%input, %launch_w=%weights, %launch_out=%output)
        : memref<4x16xf16>,
          memref<16x2xf16>,
          memref<4x2xf16> {
      air.segment @router_segment
          args(%seg_tok=%tok, %seg_in=%launch_in, %seg_w=%launch_w, %seg_out=%launch_out)
          : index,
            memref<4x16xf16>,
            memref<16x2xf16>,
            memref<4x2xf16> {
        %c0 = arith.constant 0 : index
        %c1 = arith.constant 1 : index
        %c2 = arith.constant 2 : index
        %c_hidden = arith.constant 16 : index
        %l2_in = memref.alloc() : memref<1x16xf16, 1>
        %l2_w = memref.alloc() : memref<16x2xf16, 1>
        %l2_out = memref.alloc() : memref<1x2xf16, 1>

        air.dma_memcpy_nd (%l2_in[%c0, %c0] [%c1, %c_hidden] [%c_hidden, %c1],
                           %seg_in[%seg_tok, %c0] [%c1, %c_hidden] [%c_hidden, %c1])
            : (memref<1x16xf16, 1>,
               memref<4x16xf16>)
        air.dma_memcpy_nd (%l2_w[%c0, %c0] [%c_hidden, %c2] [%c2, %c1],
                           %seg_w[%c0, %c0] [%c_hidden, %c2] [%c2, %c1])
            : (memref<16x2xf16, 1>,
               memref<16x2xf16>)

        air.herd @router_herd
            tile (%tx, %ty) in (%sx=%c1, %sy=%c1)
            args(%herd_in=%l2_in, %herd_w=%l2_w, %herd_out=%l2_out)
            : memref<1x16xf16, 1>,
              memref<16x2xf16, 1>,
              memref<1x2xf16, 1> {
          %h0 = arith.constant 0 : index
          %h1 = arith.constant 1 : index
          %h2 = arith.constant 2 : index
          %h_hidden = arith.constant 16 : index
          %zero = arith.constant 0.0 : f16
          %l1_in = memref.alloc() : memref<16xf16, 2>
          %l1_w = memref.alloc() : memref<16x2xf16, 2>
          %l1_out = memref.alloc() : memref<2xf16, 2>

          air.dma_memcpy_nd (%l1_in[%h0] [%h_hidden] [%h1],
                             %herd_in[%h0, %h0] [%h1, %h_hidden] [%h_hidden, %h1])
              : (memref<16xf16, 2>,
                 memref<1x16xf16, 1>)
          air.dma_memcpy_nd (%l1_w[%h0, %h0] [%h_hidden, %h2] [%h2, %h1],
                             %herd_w[%h0, %h0] [%h_hidden, %h2] [%h2, %h1])
              : (memref<16x2xf16, 2>,
                 memref<16x2xf16, 1>)

          scf.for %j = %h0 to %h2 step %h1 {
            memref.store %zero, %l1_out[%j] : memref<2xf16, 2>
          }

          scf.for %j = %h0 to %h2 step %h1 {
            scf.for %k = %h0 to %h_hidden step %h1 {
              %in_val = memref.load %l1_in[%k] : memref<16xf16, 2>
              %w_val = memref.load %l1_w[%k, %j] : memref<16x2xf16, 2>
              %acc = memref.load %l1_out[%j] : memref<2xf16, 2>
              %prod = arith.mulf %in_val, %w_val : f16
              %next = arith.addf %acc, %prod : f16
              memref.store %next, %l1_out[%j] : memref<2xf16, 2>
            }
          }

          air.dma_memcpy_nd (%herd_out[%h0, %h0] [%h1, %h2] [%h2, %h1],
                             %l1_out[%h0] [%h2] [%h1])
              : (memref<1x2xf16, 1>, memref<2xf16, 2>)
          air.herd_terminator
        }

        air.dma_memcpy_nd (%seg_out[%seg_tok, %c0] [%c1, %c2] [%c2, %c1],
                           %l2_out[%c0, %c0] [%c1, %c2] [%c2, %c1])
            : (memref<4x2xf16>,
               memref<1x2xf16, 1>)
        air.segment_terminator
      }
      air.launch_terminator
    }
    return
  }
}
