//===- identical_shim_put_run_bound_seq.mlir --------------------*- MLIR -*-===//
//
// Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

// RUN: air-opt -airrt-to-npu %s | FileCheck %s

// THE POST-CONVERSION CASE, and the reason this file exists apart from
// identical_shim_put_run_bound.mlir. That test's input is a hand-written
// `func.func` -- the PRE-conversion shape, which this pass itself converts to
// `aie.runtime_sequence` (its CHECKs expect the converted form). But a module
// can also ARRIVE with the runtime sequence already formed: R1's real module
// presents `aie.device(npu2)` holding `aie.runtime_sequence`, with the six
// identical `@air_channel_2` configures living INSIDE it (doc 52 SS12). The
// step shipped walking `func::FuncOp` only, so on that module it found only
// empty declarations and NEVER FIRED -- while its lit stayed green, because
// the lit exercised the shape aircc does not present. Five device arms
// re-measured pre-fix behaviour before anyone noticed (devq 334, queue row
// 28(b)).
//
// So this input IS the arrived-converted shape -- generated by running the
// pass on the sibling test's module with DISTINCT refill offsets (so the run
// was left alone), then restoring the six offsets to identity by text. A lit
// in the pre-conversion shape can never cover this: the two shapes take
// different branches of the traversal, and this file is the branch the real
// pipeline takes.
//
// VERIFIED FAILING PRE-FIX: the binary without the RuntimeSequenceOp walk
// leaves this module untouched -- one issue_token (@out's own), one await --
// so every CHECK below on the @refill run fails against it.

// CHECK-LABEL: aie.runtime_sequence @identical_put_run

// The output S2MM stays armed first, and keeps its own token.
// CHECK: aiex.dma_configure_task_for @out
// CHECK: issue_token = true

// The negative control: six DISTINCT-offset transfers on @varying are a real
// multi-part transfer, not an unfolded loop -- untouched, fire-and-forget.
// CHECK: %[[V0:.*]] = aiex.dma_configure_task_for @varying
// CHECK-NOT: issue_token
// CHECK: aiex.dma_start_task(%[[V0]])

// @weights precedes the paced run: an await that blocks before a consumer's
// other operand has been issued is a hang, so the sink invariant holds in the
// sequence shape exactly as in the func shape.
// CHECK: aiex.dma_configure_task_for @weights
// CHECK: aiex.dma_start_task

// The identical run fires HERE, in the arrived-converted module: every task
// issues a completion token, and the run is paced at depth 2 -- the await
// that makes room runs before the configure that takes the ID.
// CHECK: %[[R0:.*]] = aiex.dma_configure_task_for @refill
// CHECK: issue_token = true
// CHECK: aiex.dma_start_task(%[[R0]])
// CHECK: %[[R1:.*]] = aiex.dma_configure_task_for @refill
// CHECK: aiex.dma_start_task(%[[R1]])
// CHECK: aiex.dma_await_task(%[[R0]])
// CHECK: aiex.dma_configure_task_for @refill

// The in-flight tail is drained, and no token this step created leaks into a
// free: the run's clustered per-transfer frees are gone.
// CHECK: aiex.dma_await_task
// CHECK-NOT: aiex.dma_free_task(%[[R0]])

module {
  aie.device(npu1) @identical_put_run_seg {
    %shim_noc_tile_0_0 = aie.tile(0, 0)
    %shim_noc_tile_1_0 = aie.tile(1, 0)
    %shim_noc_tile_2_0 = aie.tile(2, 0)
    %shim_noc_tile_3_0 = aie.tile(3, 0)
    aie.shim_dma_allocation @refill(%shim_noc_tile_0_0, MM2S, 0)
    aie.shim_dma_allocation @varying(%shim_noc_tile_1_0, MM2S, 0)
    aie.shim_dma_allocation @weights(%shim_noc_tile_3_0, MM2S, 0)
    aie.shim_dma_allocation @out(%shim_noc_tile_2_0, S2MM, 0)
    aie.runtime_sequence @identical_put_run(%arg0: memref<1024xi32>, %arg1: memref<1024xi32>, %arg2: memref<1024xi32>) {
      %0 = aiex.dma_configure_task_for @out {
        aie.dma_bd(%arg2 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      } {issue_token = true}
      aiex.dma_start_task(%0)
      %1 = aiex.dma_configure_task_for @varying {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%1)
      %2 = aiex.dma_configure_task_for @varying {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 32 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%2)
      %3 = aiex.dma_configure_task_for @varying {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 64 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%3)
      %4 = aiex.dma_configure_task_for @varying {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 96 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%4)
      %5 = aiex.dma_configure_task_for @varying {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 128 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%5)
      %6 = aiex.dma_configure_task_for @varying {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 160 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%6)
      %7 = aiex.dma_configure_task_for @refill {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%7)
      %8 = aiex.dma_configure_task_for @refill {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%8)
      %9 = aiex.dma_configure_task_for @refill {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%9)
      %10 = aiex.dma_configure_task_for @refill {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%10)
      %11 = aiex.dma_configure_task_for @refill {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%11)
      %12 = aiex.dma_configure_task_for @refill {
        aie.dma_bd(%arg0 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%12)
      %13 = aiex.dma_configure_task_for @weights {
        aie.dma_bd(%arg1 : memref<1024xi32> offset = 0 len = 32 sizes = [32] strides = [1])
        aie.end
      }
      aiex.dma_start_task(%13)
      aiex.dma_await_task(%0)
      aiex.dma_free_task(%1)
      aiex.dma_free_task(%2)
      aiex.dma_free_task(%3)
      aiex.dma_free_task(%4)
      aiex.dma_free_task(%5)
      aiex.dma_free_task(%6)
      aiex.dma_free_task(%7)
      aiex.dma_free_task(%8)
      aiex.dma_free_task(%9)
      aiex.dma_free_task(%10)
      aiex.dma_free_task(%11)
      aiex.dma_free_task(%12)
      aiex.dma_free_task(%13)
    }
  }
}

